### ISSUE TITLE
Reduce size of API production image

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#1008]
## Problem

Development python packages are included in the final production image for the API <s>and the Ingestion Server</s>. Those aren't needed there and represent a risk; we should be able to remove them easily following a strategy similar to the Catalog with a [docker-compose.yml](https://github.com/WordPress/openverse-catalog/blob/main/docker-compose.yml) / [docker-compose.override.yml](https://github.com/WordPress/openverse-catalog/blob/main/docker-compose.override.yml) files.

## Description

Exclude `dev` packages from the **[openverse-api](https://github.com/WordPress/openverse/pkgs/container/openverse-api)** <s>and [**openverse-ingestion_server**](https://github.com/WordPress/openverse/pkgs/container/openverse-ingestion_server)</s> images.

**Comment by dhruvkb** [comment]
I have reduced the scope of this issue to only cover the API and not the ingestion server because 

- The ingestion server does not use PDM so optimising it will be a separate endeavour that cannot share effort with the same endeavour for API.
- The ingestion server is already planned to be phased out so there is not much to gain by optimising it in its current deprecated form.
