### ISSUE TITLE
Unhandled exception when reading image in watermark route

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1234]
## Sentry link

https://openverse.sentry.io/share/issue/4a58dbfe0f544a3b9cc93227db6d3c80/

## Description

The watermark route is deprecated but still live.

https://github.com/WordPress/openverse/blob/main/api/catalog/api/utils/watermark.py#L164-L171

We only catch network exceptions. We should either expand the exceptions list to include catching errors that come from trying to read the image or move reading the image into a separate try/except block after the request is successful. The latter is preferable as we'd be able to know _what_ caused the issue more clearly rather than stuffing all the handling into a single block.

## Additional context

Marking priority low because the endpoint is deprecated, even though ideally the application would not 500.

**Comment by obulat** [comment]
This is an example endpoint that causes this exception:

http://localhost:50280/v1/images/c0768c3c-cac4-4838-81b6-ca875712f398/watermark/

This particular image returns 404: https://live.staticflickr.com/65535/51747301466_2ccdb5bf9d_b.jpg

This is a part of the response you get:
```
UnidentifiedImageError at /v1/images/c0768c3c-cac4-4838-81b6-ca875712f398/watermark/
cannot identify image file &lt;_io.BytesIO object at 0xffff85a4a2f0&gt;

Request Method: | GET
-- | --
http://localhost:50280/v1/images/c0768c3c-cac4-4838-81b6-ca875712f398/watermark/
4.2.4
UnidentifiedImageError
cannot identify image file <_io.BytesIO object at 0xffff85a4a2f0>
/venv/lib/python3.11/site-packages/PIL/Image.py, line 3298, in open
api.views.image_views.ImageViewSet
```

**Comment by obulat** [comment]
Possible solution for this issue:

1. Add an `UpstreamWatermarkException` to the top of `apiapi/utils/watermark.py` file with the following data (similar to `UpstreamThumbnailException`):
```
+class UpstreamWatermarkException(APIException):
    status_code = status.HTTP_424_FAILED_DEPENDENCY
    default_detail = "Could not render watermarked image due to upstream provider error."
    default_code = "upstream_watermark_failure"
```

1. Add error handling to the `_open_image` function
After `response = requests.get(url, headers=HEADERS)`, add `response.raise_for_status` so that an exception is thrown when the response has a status other than success (200). Then, in the `except` clause of the same function, instead of returning `None, None`, raise the `UpstreamWatermarkException`.

This way, `_open_image` will only return valid image data, or short-circuit to display an error response.

**Comment by akhilsrivatsa** [comment]
Is this open? Can I pick this up?

**Comment by obulat** [comment]
Sure, @akhilsrivatsa ! I'll assign this to you, thank you :)
