### ISSUE TITLE
Image source: justtakeitfree.com

### ISSUE THREAD

**Issue by Aventurier** [WordPress/openverse#1264]
### Source Site

https://justtakeitfree.com/

### Value Provided

It's an independent project from ukrainian family. We host only our photos.

### Licenses Provided

CC BY 4.0

### Implementation

- [X] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
Without a response from @Aventurier regarding the API, I think we should plan to scrape. There are currently 6 pages of results and around 178 results (based on https://justtakeitfree.com/photo/178/ existing and anything beyond that like https://justtakeitfree.com/photo/179/ and https://justtakeitfree.com/photo/180/ returning a 404, though https://justtakeitfree.com/photo/1/ also 404s). If the DAG requested one page every two seconds it would only take around 6 minutes to ingest the entire provider. We could do that monthly to reduce impact from the scraping.

Seems doable and I think the assumption that we can scrape is safe considering the volume and lack of ToS.

As for the title to use, the site itself appears to use the first tag in the list of tags for the filename when you click the download link. We can do the same.

Regarding the attribution, the author should be as Dhruv mentioned "Justtakeitfree Free Photos". Based on the text of the issue ("We host only our photos") it sounds like that's an appropriate attribution to credit the creators. I dumped EXIF on one of the images and there is nothing to suggest otherwise.

So to clarify the DAG implementation:

- Make iterative requests to `https://justtakeitfree.com/photo/<i>/`, incrementing `i` once every two seconds. Go until 10 404s are returned in a row.
- DAG should run monthly
- The license is CC-BY 4.0 for all works
- Creator is "Justtakeitfree Free Photos" for all works.
- Provider/source is "justtakeitfree.com"
- Foreign landing URL is `https://justtakeitfree.com/photo/<i>/` for the work
- URL is `https://justtakeitfree.com/photos/<i>_800.jpg` for the work (full sized is available on the landing page)
- No special thumbnail URL, the `_800.jpg` version is used as the thumbnail on the site

**Comment by Aventurier** [comment]
I'm sorry for long pause. Actually I did small API that can search for an images by tag and retrieve information about image.
https://justtakeitfree.com/api/api.php?key=vj45mub435v6bsdf90&query=search&tag=grass
It's an example how to find images by tag (you can use the key that is in example).
If you have any question or you want me to extend an API, please, write.
Thanks.

**Comment by sarayourfriend** [comment]
No worries, Aventurier! Thanks for letting us know. Can you share whether there is a way to paginate through the API? For Openverse's catalogue to be able to get all the images, we'd need to be able to use the API to paginate through all the images rather than for just particular tags. Something like:

https://justtakeitfree.com/api/api.php?page=1
https://justtakeitfree.com/api/api.php?page=2
https://justtakeitfree.com/api/api.php?page=3
https://justtakeitfree.com/api/api.php?page=4

etc., without any query terms.

Is the email on the privacy policy page the best location to get in touch regarding a key specifically for Openverse (to avoid the secret leaking publicly)?

**Comment by zackkrida** [comment]
@Aventurier amazing! Thank you so much. You can email us at openverse@wordpress.org with a new key.

**Comment by krysal** [comment]
API key received. Thank you, @Aventurier!
