### ISSUE TITLE
Capture thumbnails for Rawpixel

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#1401]
## Description

For context, see the refactor PR: https://github.com/WordPress/openverse-catalog/pull/795#discussion_r1002145671

Presently we do not have a well-defined field for thumbnails. We will be deciding where thumbnails will go in a discussion on our [Make WP blog](https://make.wordpress.org/openverse/), but until we do it's best to exclude this field for now. This issue is blocked until a decision is made.

A potential implementation is available in the above linked PR.

## Additional context

WordPress/openverse#1450, https://github.com/WordPress/openverse-catalog/pull/796#issuecomment-1287422102

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by krysal** [comment]
We haven't had any problems with huge images coming from Rawpixel so I wonder if it is worth continuing with this task 🤔 Since this is related to #905 I'll add Rawpixel as an item there and close this issue. Adding thumbnails without specific guidelines has been more of a problem than it has helped.
