### ISSUE TITLE
Add explicit opt-in for analytics/telemetry or make opting out possible, easy, and evident

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#176]
## Problem

We do not currently ask for consent to collect anonymized analytics data. We also do not currently offer any way of opting out of analytics gathering.

**Note:** Analytics is currently turned _off_ in production. cc @zackkrida to confirm; we're not using it in any case so we should turn it off until we decide how to solve this problem if it's not already off. With that in mind, we should feel free to explore the options I suggest below and any other alternatives we can think of for how to be responsible stewards of our user's data. 

## Description

We could implement a banner similar to Syncthing's Telemetry banner:

![Syncthing's first-run banner asking for consent to send anonymized analytics data with clear "yes" and "no" options](https://user-images.githubusercontent.com/24264157/155587739-8966f986-e794-4469-b739-3fc03d1478ea.png)

Note that they also share the aggregated data up front and publicly at https://data.syncthing.net/.

A lot of other OSS projects that gather telemetry at least let you know about it when you first run their program so you can choose to opt-out if you'd like. In my personal opinion, asking for opt-in is better, but can be more intrusive depending on how it's done (or potentially have a lower positive conversion rate when done less-intrusively). For example, showing an analytics consent popover when someone first lands on the homepage can have a pretty negative effect on the experience. There are probably solutions to this though that still gather data from first interaction while still waiting for consent before sending the events home.

For example, we could start measuring whatever we want immediately after the user lands on the page but just cache the events locally and don't send them off yet. Then show a cookie-disclosure style banner at the bottom of the screen asking if they'd like to opt-in to sharing anonymized usage data with us. If they say yes, then send all the previous events and store a setting saying that they've opted into sharing the data. If the setting is detected from the offset as being off, then don't even create the event cache that would be sent, just throw away the events completely.

Ideally the consent banner would use clear and plain language and have simple to understand "yes, participate in anonymous data collection" and "no, do not share my anonymized behavior data" buttons. Cookie consent banners are full of anti-patterns, begging the user to just hit "accept" as they resign themselves to a world that is intent on tracking their every move. Trying to disable cookies for a website is often a frustrating and confusing experience with the various different levels of cookies that you can individually toggle on and off. It's confusing and unpleasant and we should avoid replicating that kind of experience.

If we went the opt-out route, we'd still need to find a way to let users know that that is possible. I don't know how you would do that less-intrusively while still respecting the user's privacy. If the user isn't aware that they can opt-out then essentially you've made the choice for them and there might as well not even be the ability to opt-out. You can't obscure "revoking consent" (scare quotes because having to opt-out of something you were never asked about to begin with isn't really _revoking_ considering consent was never solicited to begin with) and still call it "consent."

When only providing a method for opting-out (i.e., assuming consent), even if the data is "sufficiently anonymized," we're still (as application developers) assuming we know what constitutes as "sufficiently anonymized" for an individual user. We cannot and should not assume such authority over the privacy concerns for an individual. That's why below I propose making what data is collected, how we collect it, and why we collect it as clear and easy to understand as possible.

It would also go a long way in gaining user trust about the data if we described, in detail, what and why we collect it. Similar to the plan for the Cookie explanation on the privacy policy page, if we could draft a straightforward and easy to understand document that laid out exactly what events are tracked, what data is gathered for them, why, and how we ensure that the data can't be used to track an individual user once it's been stored. Without that I'd even say that we can't solicit consent for the opt-in version in good faith: how can you opt-in to something you don't understand (or even have access to resources for understanding)?

Likewise if we could copy Syncthing's idea and openly publish the aggregated data, that could also help.

Either way we go, we should make it possible (and easy) for users to reverse their decision at any time. If they'd like to opt-out after having opted-in, that should be possible. If for whatever reason someone want's to opt-in after having opted-out or refused to give consent to begin with, that should also be possible. Additionally, if the data collected ever changes, for users who have opted-in, we should inform them of the changes and confirm that they still consent to the data collection.

## Alternatives

There are probably some alternative approaches we could take. Of course we could do nothing, but I think that would be a net-negative for us. We could stop collecting usage data altogether and instead rely on API requests stripped of IP and other finger-printing request headers (like language, UA, etc) from the frontend for most things. That would be worth looking into, whether the data we're collecting is even necessary.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by AetherUnbound** [comment]
I love the idea of making whatever data we collect public and accessible. The example from the site you link is pretty rad.

I can't say I really have a preference on this. I _do_ think that we're likely to get far, far less data with an opt-in model than an opt-out-with-clearly-presented-choice one. 

I think the first step, before deciding any course of action, is determining *what* information we want to collect that we couldn't get through API requests. That will help inform which of the proposed alternatives we might pursue.

**Comment by stacimc** [comment]
> Note that they also share the aggregated data up front and publicly at https://data.syncthing.net/.

This is very cool and something I'd love for us to do!

> It would also go a long way in gaining user trust about the data if we described, in detail, what and why we collect it.

💯 This feels vital to me.

This is an excellent write up and captures the pros and cons of various approaches well. Understanding that the intrusiveness is a concern, I'd still prefer an intrusive banner with clearly presented choices.

I also agree strongly that users should have the ability to change their choice and should be informed of updates to collected data.

**Comment by sarayourfriend** [comment]
> I think the first step, before deciding any course of action, is determining what information we want to collect that we couldn't get through API requests. That will help inform which of the proposed alternatives we might pursue.

Totally. It seems like that's likely a good place to start. I imagine that on some level the model we choose to adopt for how to ask for, store, and manage user consent could be informed by the data we're collecting (that wouldn't exist in our request logs anyway, like search query params for example, single result page visits, etc).

**Comment by zackkrida** [comment]
Such a great writeup; thanks @sarayourfriend! I have many thoughts:

- Analytics _is_ disabled in production
- [Here](https://github.com/WordPress/openverse-frontend/blob/67f0677eb662a06d2e7b6b23343132483d7961f8/src/data/usage-data-service.js#L50) are all of the analytics events. The only thing here that can't be interpreted from simply looking at our requests is the session UUIDs, which you [recently worked on](https://github.com/WordPress/openverse-frontend/pull/798). I imagine if we were using this data, it would be for things like determining how many searches users typically need to make to find an image, and other paths like that.
- I'd be very open to 🗑️-ing the analytics server, and simply using requests to our api endpoints for any analysis we do.
- Publishing any user research or datasets in 10000000% something we should do.

With regard to user consent and opt-in; here's my problem. I think far more pernicious than anything _we're_ collecting is the fact that we're using third-party platforms like AWS and CloudFlare, which _do_ collect things like IP addresses of end users. Even the fact that we probably have IP addresses in our server logs, for example, and which _is live in production_, seems worse to me than our current analytics collection, which, again, is disabled. 

Here are AWS and CloudFlare's privacy/data policies, which seem to indicate they can do whatever they want with user data:

- https://aws.amazon.com/compliance/data-privacy-faq/
- https://www.cloudflare.com/privacypolicy/

Here are options are to switch platforms, or tell people not to use Openverse in order to let users opt out of giving their information to these providers. Before doing so, any attempts we make to give users the ability to consent into our _analytics_ strike me as at best illusory and at worst manipulative.

**Comment by sarayourfriend** [comment]
Very good point about AWS and CloudFlare; that's also not something I _ever_ see disclosed and doesn't seem to be part of most people's expectation of privacy. There are also separate models for privacy: someone could trust Amazon (however debatable that trust may be from our own personal and professional opinions) but not trust _us_ with that same data. There are also privacy models that say "relent to unavoidable infringement by the central infrastructure providers but resist any unnecessary _extra_ infringement as much as possible" though what subset of Openverse users that idea appeals to is probably unknowable and most likely small.

In any case, it does seem to be good practice to make it easy to manage the permissions for _our_ application and to disclose what and why you collect any data. We have very clear and immediate ways to control those options (with relatively low effort compared to the infrastructure issue).

The infrastructure of the modern web is a wholly different question. You can't (or at least it takes quite some effort) to opt out of or evade your ISP taking a look at your online activity. And it's basically impossible to opt out of or evade state actors. It's also structurally impossible to use the internet and opt out of CloudFlare, AWS, GCP, Azure, Alibaba, and others.

To that end, however, insofar as we can control where we serve our applications from, it's probably worth evaluating. And in particular worth evaluating whether any significant percentage of our users will care about that (i.e., is it actually worth the engineering effort to make a significant change like that versus implementing new or improving existing features on the platform). Then again, I'm not sure what the options really are. A certain subset of users won't be happy with their data stored outside of the US for example.

Where is WordPress.org hosted?

**Comment by panchovm** [comment]
Thanks for bringing this issue ❤️  I had in my task list working on how to run quantitative user research in parallel with the [Outreach Program](https://make.wordpress.org/test/handbook/full-site-editing-outreach-experiment/) initiative.

> I think the first step, before deciding any course of action, is determining what information we want to collect that we couldn't get through API requests. That will help inform which of the proposed alternatives we might pursue.

I strongly agree with @AetherUnbound in that sentence, and to know what questions regarding openverse success we need to answer.

Overall, I believe in being transparent as much as possible. We are facing an era where transparency is urgent and open-source tools are situated in possible pernicious uses. Avoiding the topic sounds like the worst-case scenario to me.

That being said, and to @zackkrida's point about data stored and managed by third-party platforms, I think we should inform that situation in plain language and be explicit on recommending not using Openverse if data stored concerns you as a visitor. 

To the experience of understanding and opting on how to treat personal data, I am drawn to the opt-out solution in the search result plus a clear description on the homepage.

The good experience is a design challenge that I am happy to get my hands-on. Overall, I am not concerned about lower conversion rates as the strategic decisions lay primarily on contributors' vision about _what's best for openverse_ rather than business goals. Whereas allowing data control can gain community trust in the tool.

> We should make it possible (and easy) for users to reverse their decision at any time. If they'd like to opt-out after having opted-in, that should be possible. If for whatever reason someone want's to opt-in after having opted-out or refused to give consent to begin with, that should also be possible

With that in mind, the user flow I envision consists of two instances.
1. Show clearly that openverse collects data that you can set once browsing content.
2. Have an openverse settings feature to enable/disable the data shared.

The idea above has no technical review at all (sorry for that), and I hope it can be developed. But I think there is an opportunity for us to treat the data collection setting integrated with the search experience rather than popover-ing very unfriendly messages.

**Comment by sarayourfriend** [comment]
The approach being taken in #312 supersedes this suggestion. We're going with default opt-in because our analytics are not able to be de-anonymised. If the latter changes we can revisit this.
