### ISSUE TITLE
Identify fields from which the license can be obtained for certain Smithsonian museums (original #472)

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#1778]
This issue has been migrated from the [CC Search Frontend repository](https://github.com/creativecommons/cccatalog/issues/472)

```
Author: ChariniNana
Date: Mon Jul 27 2020
Labels: ✨ goal: improvement,🙅 status: discontinued
```
## Current Situation
In the existing implementation of the Smithsonian provider API script, the license value is obtained from the `content.descriptiveNonRepeating.usage.access` field. Only the images with a license value _CC0_ are stored in the image DB. However, for two of the Smithsonian museums (FBR - smithsonian_field_book_project, and NAA - smithsonian_anthropological_archives) this field is unavailable and thus we lose all their images due the inability of identifying their public domain status.

## Suggested Improvement
Identify an alternative field from which to obtain the license

## Benefit
Considerable improvement to the completeness of Smithsonian data

## Additional context
Related to WordPress/openverse-catalog#397

**Comment by sarayourfriend** [comment]
Based on https://sirismm.si.edu/siris/EDAN_IMM_OBJECT_RECORDS_1.09.pdf, `usage.access` is the correct and only place to find information about access rights for an object.

@obulat do you know if there is indication that there actually are other metadata locations where we could reliably retrieve access information for an object? Their own documentation does not make it seem that way, and even if it is, it's certainly not the _documented_ way to do it.

If we don't have an actual approach for this, then the issue needs to either be closed (my preference, it's nice to get more data but we don't need it, especially if the access information isn't reliable) or updated to reflect the fact that it's actually a research issue, rather than an implementation.

**Comment by sarayourfriend** [comment]
Actually, I'm going to proactively close this based on my research, but if anyone knows something about this that indicates that we should be able to find reliable access information for these works, please reopen the issue and add actionable details so that it can be worked on.
