### ISSUE TITLE
RFC Request: Feature Flags

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#178]
We need an RFC outlining a proposal for feature flagging in the Openverse frontend. Previously, we've just used boolean environment variables, but ideally we could set flags with a query parameter and have some frontend components or composables to help assist with this work.

Such functionality would be useful for _large features_; instead of basing all PRs for a feature against a feature branch, that must be kept in sync, we could simply make all functionality conditional to the feature flag instead.

Finally, we might want a 'kill switch' that makes all or select feature flags 'locked' to their default values, as a method of preventing people from running code we don't want them to in production.

Past discussion:

- https://github.com/WordPress/openverse/pull/171#discussion_r811500414
- https://github.com/WordPress/openverse-frontend/issues/889

**Comment by zackkrida** [comment]
CC @sarayourfriend who has expressed interest in this functionality previously, and may have suggestions.

**Comment by sarayourfriend** [comment]
Here are some suggestions based on past experiences that could work.

0. Add a feature flag table in the API that is readable via the API. Flags could have three available settings: `DISABLED`, `SWITCHABLE` (there's probably a better word for this), `ENABLED`. This table should be editable via the Django admin.
    * `DISABLED` means the flag cannot be turned on in the client
    * `SWITCHABLE` means the client can turn the flag on or off at their discretion
    * `ENABLED` means the flag cannot be turned off in the client
1. Load feature flag availability when the application loads on the server. The API view could return a JSON dictionary `{ [flagName: string]: 'switchable' | 'enabled' }`. Exclude `disabled` flags altogether, there's no reason for the client to know about them, any checks against them should always resolve to false (`disabledFeatureFlag in flags`). Put this into a store or the Nuxt context or something and create a supplemental context or store object of currently enabled flags, setting all the `enabled` flags to `true` and the `switchable` flags defaulting to `false`.
2. Use query params to flap switchable feature flags on and off for a session and store the value in a cookie. Only allow settings to be switched if they're set to `switchable` according to the API response.
    * For example, if a flag for 3d models exists, to switch it on you would just add `feature--3d_model=true` to your SSR request. This would set it to "on" in a session cookie and in the store/context. This should happen before the app renders anything, so in a server middleware. To turn it back off for your session, simply set the same query to `false`: `feature--3d_model=false`.

This is more or less how Django Gargoyle works. https://github.com/YPlan/gargoyle

Gargoyle is great actually and has a ton of cool features but I'm not sure how well it would work with the server rendering happening in a different context. I only ever used it when rendering using Django (even when using React we would throw the flags into a global template variable for the JS app to bootstrap with).

Gargoyle has a ton more features that allow using it for a/b testing, things like being able to set flags on or off for some percentage of clients, etc. Creating cohorts, setting flags geographically, etc. All these are things I don't foresee us needing any time soon. Maybe a/b testing but honestly we're far away from having the capacity for doing stuff like that effectively. For that reason I'd recommend against adopting Gargoyle or any of the other feature flag frameworks I'm aware of... they're all similarly focus on solving a huge surface area of problems that have nothing to do with what we're trying to accomplish currently.

My gut feeling is that we should only use feature flags on the frontend, or at least try as hard as possible to avoid feature flags on the API. For the API we could create an `unversioned` or `beta` version prefix. So instead of `api.openverse.engineering/v1/3d-models/...`, while the feature is still in development we'd deploy the 3d models endpoints to `api.openverse.engineering/beta/3d-models` or `/unversioned/3d-models` or some other version prefix like that that would dissuade anyone from depending on it.

Remember that feature flags, over time, if unmaintained and accrued, add immense complexity to an application that we would do well to avoid. It's a nightmare to end up in a situation where an app doesn't work or behaves strangely unless a certain set of base feature flags are configured in a specific way.

I'd love for the RFC to cover a "recovery plan" of sorts for once a flag is set to `enabled` (i.e., permanently on for everyone). Once that happens, I think we'd want to cut some high priority tickets to remove the flag checks on the frontend and delete all the dead code in the `else` branch for the flag check.

**Comment by sarayourfriend** [comment]
By the way, @stacimc and I used Gargoyle at the same time on the same projects. She might remember some details about it I'm forgetting or features that might be useful for it.

Anyone else have experience with different approaches to feature flags? My only experience was with Gargoyle and my suggestions above are quite literally me just paring down what Gargoyle did to the "essential features" that we'd need to accomplish our purposes. I'm sure there are some other approaches we could take.

It also occurred to me that we could do some simple stuff just using a redis store or something and not even Django admin in front of it, just have some kind of token based authentication for manipulating the keys via REST. Though to be honest I'm not sure there'd be a worthwhile performance benefit from it.

**Comment by AetherUnbound** [comment]
> My gut feeling is that we should only use feature flags on the frontend, or at least try as hard as possible to avoid feature flags on the API. For the API we could create an `unversioned` or `beta` version prefix. So instead of `api.openverse.engineering/v1/3d-models/...`, while the feature is still in development we'd deploy the 3d models endpoints to `api.openverse.engineering/beta/3d-models` or `/unversioned/3d-models` or some other version prefix like that that would dissuade anyone from depending on it.

I **love** this idea!

**Comment by stacimc** [comment]
My only experience with feature flags has been with Gargoyle ^ Your breakdown here sounds good to me. Gargoyle does have a ton of features -- flag inheritance is the other one I was thinking of, you can have a parent flag that can be used to switch off all of its children at once, for example. I'm not particularly confident making a judgment call about what capabilities we'll _eventually_ need but it definitely seems safe to say that Gargoyle/similar frameworks are probably too heavy handed.

The `disabled | enabled | switchable` settings and ability to switch via query params 🎉  sounds like a great lightweight solution to me 💯 

> I'd love for the RFC to cover a "recovery plan" of sorts for once a flag is set to enabled (i.e., permanently on for everyone). Once that happens, I think we'd want to cut some high priority tickets to remove the flag checks on the frontend and delete all the dead code in the else branch for the flag check.

➕ !!

**Comment by sarayourfriend** [comment]
> flag inheritance is the other one I was thinking of, you can have a parent flag that can be used to switch off all of its children at once

Oh wow I totally forgot about that. That was definitely a very useful feature for goegraphical based testing and releasing IIRC... and being able to turn off feature groups that had multiple different sub-cohorts that were failing whatever metric we were measuring.

Maybe one day Openverse will need such things :slightly_smiling_face:

I'll also note that my other experience with feature flags is when I worked on Automattic's Calypso project. There I think flags were wholly separate from the a/b testing framework. Now that I think about it Calypso's feature flag implementation is roughly similar to the "simple" query param approach, with one difference being that they've got a json blob per deployment environment to set the defaults rather than storing them in a DB. We could do that too actually and would probably be a _lot_ simpler _and_ would remove the blocking request at the top of every SSR request.

We'd introduce `features/{local,staging,production}.json` files that are the mapping of flag names to `disabled | switchable | enabled`. _However_, that wouldn't allow us to switch flags without deploying, which could work against us.

If we wanted to go _really_ bare-bones, we could create a separate branch in the Openverse-frontend repository that only has the environment feature JSON blobs and any push to it uploads the JSON to a public-read S3 bucket that Nuxt pulls from on each request. Adds back the request but makes it easier/faster to manipulate flags without having to do a whole deployment of the frontend. Based on the staging deployments for the dockerized frontend, those take around 8 minutes it seems. I'm not sure how much pressure we'd have where we couldn't wait 8 minutes to roll back a feature flag being toggled on erroneously.

Just throwing out some more options to consider for the RFC :sweat_smile:

**Comment by krysal** [comment]
@zackkrida was this closed by mistake? The RFC of @dhruvkb is still open.

**Comment by zackkrida** [comment]
@krysal it's a bit silly, but this was just an issue to make sure the RFC was _created_. We can continue to discuss and track in the RFC PR itself.
