### ISSUE TITLE
Remove `catalog/requirements_tooling.txt`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#1844]
## Problem

This file appears to no longer be needed as `pre-commit` installation is handled by the monorepo.

## Description

@AetherUnbound @stacimc can y'all confirm whether this issue is valid? Blocked until verification.

Remove the unneeded `catalog/requirements_tooling.txt` file.

**Comment by dhruvkb** [comment]
I agree with removing it, considering it's only purpose was to install pre-commit, which is now handled by the monorepo management. However, it is being referenced in the catalog's `justfile`, so that will also need to be dropped.

https://github.com/WordPress/openverse/blob/10ea15a59dd8bb6c142cb94c309c658377edbacc/catalog/justfile#L52
