### ISSUE TITLE
Postmortem improvements from "Openverse degraded performance 2023-05-03"

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2060]
Make post for the incident: [Openverse degraded performance 2023-05-03](https://make.wordpress.org/openverse/2023/05/03/openverse-degraded-performance-2023-05-03/)

On 2023-05-08 the @WordPress/openverse-maintainers conducted a "5 Whys" postmortem in a Slack huddle. Here's a [Google Doc](https://docs.google.com/document/d/1VGCWR85ipt_grLbDu_mKN31RAPTNEL_emvqDj1vcg20/edit#) from the session.

This is a tracking issue with an [associated milestone](https://github.com/WordPress/openverse/milestone/10) for follow-up improvements to documentation, code, and monitoring after that incident. 

This issue can be used to facilitate discussion or link to external tickets outside of this monorepo related to this postmortem.

## Issues

- [ ] https://github.com/WordPress/openverse/issues/2063
- [x] https://github.com/WordPress/openverse-infrastructure/issues/180
- [x] https://github.com/WordPress/openverse/issues/2070
- [x] https://github.com/WordPress/openverse/issues/2071

**Comment by krysal** [comment]
I added the [Store Elasticsearch log group](https://github.com/WordPress/openverse-infrastructure/issues/180) issue. We didn't discuss it in the 5-whys session but seems important since we don't have an easy access to ES logs currently. Also added some issues @dhruvkb created to the milestone.

I was a about to create an issue for the Uptime Robot alarm but does not seem to be suitable for the use case I was thinking of. It does not have the ability to check field values (`"result_count" < 10000` in our case), only presence (or not) of “keywords”.

Lastly, @sarayourfriend:

> we should prioritise ensuring that the configuration is correct

I agree with that statement, but that routing configuration looks correct to me. I replied in the PR to the issue you linked with more details.
