### ISSUE TITLE
Save artifacts from failed Playwright test runs

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#2108]
## Problem

Identified by @obulat in the comments of #2020, currently if a flaky Playwright test causes a run to fail we don't have a way of debugging _why_ the test failed, as GitHub deletes artifacts from tests on subsequent runs.  

## Description

Write an automation which saves these artifacts. Perhaps we could also automate the creation of the `critical` issues to fix these test flakes. We'd only want these to run on CI/CD on `main`.

**Comment by sarayourfriend** [comment]
@zackkrida by "save artifacts", do you mean save them somewhere other than uploading them to GitHub?

**Comment by zackkrida** [comment]
@sarayourfriend that's a valid and possibly superior alternative approach. 

"Store" would have been a better word for me to use. For example, we could commit the artifcats to a git branch similarly to how we handle translations.

**Comment by sarayourfriend** [comment]
Translations and the doc site work in a separate branch because we squash the history each time to avoid creating huge increases to the repo size. If we pushed the artefacts to a git branch, when would we delete those artefacts? Should we expire them after a certain amount of time? This sounds a bit like caching, which S3 would be great for (we can configure a rule to automatically delete things after a period of time, in addition to some kind of manual delete if we explicitly resolve an issue related to an artefact).

**Comment by zackkrida** [comment]
Agreed on the preferable ergonomics of S3.

That said @sarayourfriend I think to your earlier point this is more of a process issue. I also don't think I've encountered this problem in the last year and suspect solving it with tech wouldn't be worth the trouble, so I'm going to close the issue.
