### ISSUE TITLE
Designs for tag, source, and creator result pages

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2113]
## Project and issues related

* Project #410 and [Project Proposal document](https://github.com/WordPress/openverse/blob/a3cdbe085c964820e31f03425b6e40d9d75a615e/documentation/projects/proposals/additional_search_views/20230424-project_proposal_additional_search_views.md)
* #562

### Single result page

The single result page allows users to land in results by tag, source, and creator. Mockups for each view are attached below.

| `xl` | `xs` |
|:---|:---|
|<img width="1440" alt="Single result page on XL breakpoint" src="https://github.com/WordPress/openverse/assets/895819/05d4bc21-ed08-4bdf-8bbf-01621cb5d61b">|<img width="375" alt="Single result page on XS breakpoint" src="https://github.com/WordPress/openverse/assets/895819/e80d9203-49bd-4a1f-a8cc-22c795c14a2c">|

As part of the design updates this project involves, the following changes were applied:

- [Tag pill](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=558-2281&t=PLtl2lI7yDBZOUdy-4) changes to a [button](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?type=design&node-id=4577-11868&t=PLtl2lI7yDBZOUdy-4) element. Button specs are described in Figma's inspect panel.
- Spacing between tags is now `12px` to ensure target area for a11y.

### Results by tag 

To land on this page, user needs to click on one of the tag components in the single result page.

| `xl` | `xs` |
|:---|:---|
|<img width="1440" alt="Tag results on XL breakpoint" src="https://github.com/WordPress/openverse/assets/895819/2512d6ad-0aaf-42f4-b570-d35eb0ca46ea">|<img width="375" alt="Tag results on XS breakpoint" src="https://github.com/WordPress/openverse/assets/895819/f6b1c15f-e6d4-4bd7-9484-49c2bec1e7c5">|

### Results by source

To land on this page, user needs to click on one of the following elements in the single result page:
- Source link below the content title
- Source link in content information section

| `xl` | `xs` |
|:---|:---|
|<img width="1440" alt="Source results on XL breakpoint" src="https://github.com/WordPress/openverse/assets/895819/ed7d954d-ba7f-471b-8f80-ba1767e22f6a">|<img width="375" alt="Source results on XS breakpoint" src="https://github.com/WordPress/openverse/assets/895819/52b763b4-9983-4c04-ad23-23a0777da20e">|

### Results by creator

To land on this page, user needs to click on one creator’s username in the single result page.

| `xl` | `xs` |
|:---|:---|
|<img width="1440" alt="Creator results on XL breakpoint" src="https://github.com/WordPress/openverse/assets/895819/88829994-3963-4929-b19e-d3b3ab57cfbc">|<img width="375" alt="Creator results on XS breakpoint" src="https://github.com/WordPress/openverse/assets/895819/76c2c095-7c95-4c64-b81b-8985623f23bf">|

## Mockups

[Figma file](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?type=design&node-id=22-13656)

---

What do you think of this idea?

**Comment by obulat** [comment]
Thank you for your detailed comment, @joedolson !

I'd like to comment on the state of the identified problems.

Point 1. I think we need to open a new issue for your first point, the accessibility of the search results count (title and h1). That problem was identified before in a larger accessibility issue (#448), and will probably require some design changes.
Point 2, accessibility of SVG license icons - will open an issue for that.
Point 3, the semantic count in the list, should be solved by #1979 that was deployed yesterday.
Point 4, the Load more button, is on our to-do list.  #2101 is the issue for it.
Point 5, indication of the page opening a new tab. We have an issue for it: #496, and even had a really good community PR. However, there were problems with it adding unnecessary spacing to the links, so we could not merge it at the time. I'll prioritize it after the Core UI improvements project is finished.
Points 6 and 7: I will open issues for the scroll to top problems.

**Comment by zackkrida** [comment]
This looks nice and elegant. It seems like an excellent way to introduce this feature without too many changes. 

I have three questions related to the overall flow:

1. Is it clear enough to users that they are in a "special" scoped view of Openverse, not the standard search flow?
2. What is the best way for users to return to the standard search flow? Just the homepage link?
3. Currently, we link to creator's external profiles on the sources. These profiles, depending on the source, allow the user to customize their profile details, contact information, or payment information. This is valuable to creators. How could we continue to link to these pages?

**Comment by obulat** [comment]
Really excited for these views!
I have several comments:

I think we should adjust the wording. "Results" seems to imply that those are the "search results". However, we are not searching here, but are displaying all items within the selected category. Is there a better word for these collections?

For the tag pages, I would expect to see the tags that look like tags instead of headings. However, I looked at other sites, and they do not look like tags either. I realized that I'm more used to seeing several tags as a way of filtering results, for example, on ecommerce sites, and we only display results for a single selected tag. So, I'm undecided whether I'd prefer the tag to look like a tag or not :)

What about providers that have several media types, such as Wikimedia and Europeana? Internally, we use separate names for them such as `wikimedia_image` and `wikimedia_audio`, but would the users expect to see both media types when they click on Wikimedia?

**Comment by AetherUnbound** [comment]
These look great, I'm so excited for these!

Presently the only restriction on our character name is that it can be no longer than 2000 character, meaning it can have any number of spaces in it. For example, we have creators like [I named my technique CONTEXTING](https://openverse.org/image/87cde4eb-960d-4ca8-9dc2-ba51c67a690d) and [Department of Visual Arts, Western University](https://openverse.org/image/0f40142a-3909-49d4-bafa-998a3156ec94) (we even have some with 'in' in it, like [Michael in San Diego, California](https://openverse.org/image/aea16b23-cdc9-4d9b-9225-d22cf19f5406) and this [absurdly long creator name I stumbled upon 😅](https://openverse.org/image/87ce0ebd-b133-4bc1-920b-016611a4b812)). That said, maybe it might make sense to visually distinguish the creator name from the provider in some way? Perhaps @zackkrida's suggestion about linking to the creator might be enough!

**Comment by zackkrida** [comment]
@fcoveram a thought I had for your consideration:

Should these views live in a modal, once implement modals for single results? Since they are not filterable or searchable, putting them in a modal over could be a way to indicate to users that they are scoped views and not the full Openverse search experience.

**Comment by sarayourfriend** [comment]
> I think it makes sense to keep “results” for tag views, but I agree could sound odd for Source and Creator. For the latter, I replaced it with “content”. This copy improvement is open to suggestions.

Just my 2¢ (and this is totally a nit, only sharing because you asked!), "Works provided by this source" or "Works by this creator" sounds more natural than "Source content" and "Creator content" . [Our about page uses both in similar places](https://openverse.org/about), so "Content provided by this source" etc would also be an improvement.

"Results tagged with <tag>" would also be more natural but then it would duplicate the queried tag unless the header was changed or combined with the contextual information, both of which would be big shifts in the page layout.

> In that vein, and following the Wikimedia example, if the single result page is an image, then the results should be images only.

In light of that, rather than "works" or "content", the specific media type would be clearer: "Images provided by this source" etc. Would tags include mixed media or also be restricted to the content type of the result page they were clicked from? If restricted, then "Images tagged with <tag>" would help clarify that as well.

I also want to say again how excited I am about this feature :slightly_smiling_face:. It's one I've felt we should have for as long as I've worked on the project.

**Comment by sarayourfriend** [comment]
Oh, another thing from the technical side: "Images tagged with" or any "tagged with" could be read (in fact, I would read it this way) as an _exact_ match on the tag, but that's not how we query them. The tags view might indeed need API work to change it to query the `tags.name.raw` field if we want it to be a true "exact" match. We probably want _some_ kind of stemming though. It'd be weird to show tags for "bird" exactly and not include works tagged "birds".

**Comment by obulat** [comment]
> Oh, another thing from the technical side: "Images tagged with" or any "tagged with" could be read (in fact, I would read it this way) as an _exact_ match on the tag, but that's not how we query them. The tags view might indeed need API work to change it to query the `tags.name.raw` field if we want it to be a true "exact" match. We probably want _some_ kind of stemming though. It'd be weird to show tags for "bird" exactly and not include works tagged "birds".

This is an interesting point. At first, I was thinking that we should **only** include the exact match. Because that's what I expect, for example, from an ecommerce site. However, our tags are different in that they do not describe mutually exclusive categories (such as "dress" and "shoes", for instance), so I do agree that we can use stemming. 
So, if the user clicks on a "bird" tag, they would get all images tagged "bird", "birds" and "birding". Which should be Okay, but the text "images tagged with bird" would be a bit misleading.
One thing I wonder about tag stemming is  whether we stem the query, too. If the user searches for "birds", do we return only images tagged "birds"? Or do we stem the query to the singular "bird" and return items tagged "bird", "birds" and "birding"?

**Comment by sarayourfriend** [comment]
> One thing I wonder about tag stemming is whether we stem the query

Query strings are subject to text analysis @obulat, and are therefore stemmed as well, yes:

> The query string is processed using the same analyzer that was applied to the field during indexing.
> 
> — [Elasticsearch Full Text Search documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/full-text-queries.html#full-text-queries)

Even if part of the query is quoted, this only enables the `PHRASE` option of ES's query string parsing ([see `PHRASE` here, which we have enabled through the default of `ALL`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#supported-flags-values)).

**Comment by zackkrida** [comment]
My initial thinking is that stemming will be _okay_ here. While they're currently tag pages, they'll be functioning more like "topic" or subject pages which is probably more useful to users in most cases anyway. Choosing to search by tag rather than an exact term inherently implies, to some extent, that the user is looking for generalized results on a particular subject.

**Comment by fcoveram** [comment]
Thanks for all the great replies. I tried different ideas based on the feedback shared and other suggestions I received internally.

Before showing the new version, here is a list with the changes applied.
* New style and interaction in "Creator" and "Source" filter buttons in single result page.
* New layout for results header in results page.
  * New copy for results description
  * Link to creator page in Creator results
  * Link to source site in Source results

## Mockups (i3)

I'm attaching `XL` and `XS` breakpoints in the same image to reduce the comment's length.

| Page | Mockup |
|:---|:---|
| Single result view. Image | <img width="2195" alt="Single result page of image in XL and XS breakpoints" src="https://github.com/WordPress/openverse/assets/895819/fce70cd9-5b5e-4da1-aa4d-e07cc7ea43a8">|
| Single result view. Audio | <img width="2195" alt="Single result page of audio in XL and XS breakpoints" src="https://github.com/WordPress/openverse/assets/895819/01f403cb-9569-4a00-b919-2cb461e12c87">|
| Creator results | <img width="2190" alt="Creator results page in XL and XS breakpoints" src="https://github.com/WordPress/openverse/assets/895819/1651e97a-af35-4895-baf6-85f9b160cd1b">|
| Source results | <img width="2195" alt="Source results page in XL and XS breakpoints" src="https://github.com/WordPress/openverse/assets/895819/8178067a-aa90-45ae-b4a1-467e02ebf21f">|
| Tag results | <img width="2195" alt="Tag results page in XL and XS breakpoints" src="https://github.com/WordPress/openverse/assets/895819/158957bc-555e-43a3-8425-e97bdad93f4f">|

### Filters in single result page

To interact with Creator and Source filters in single result page, the area is now contained within the content wrapper and left and right arrows show up to move alongside the section. Buttons has the same style as "Tag" buttons to reinforce the filtering reference.

<img width="1505" alt="Scroll interaction of Filters area in single result page of audio" src="https://github.com/WordPress/openverse/assets/895819/860102a7-3f29-4cb9-a511-3674c0a11992">

### Plausible future

In line with #424 and #425 projects, and in response to folks thoughts on the future of these pages, I think there is room for pushing Creator and Source pages to surface content more appealingly.

<img width="1720" alt="Source results page with new features" src="https://github.com/WordPress/openverse/assets/895819/c4171dd1-bda7-4a7c-8d46-222efd3a8117">

The draft attached above has the following ideas:
* **Filter indicator in the search bar.** Show the source or creator name in the search bar and disable searching within these results. Clicking on the search bar clears the filter and takes you to a normal search result after clicking on the "search" button.
* **Mutiple media views.** If the source only has Images, the switcher is disabled to prevent trying to shift to other results. But when other media exist, the switcher allows you to jump between results. This includes the All content view.
* **Filter the Creator and Source results.** Allow to filter these results and disable the ones not available.
* **Source and Creator info.** Personalize this page by displaying relevant info.
* **Sort results.** When there is no search term applied, sort by the last conent added or most popular.

All these ideas need deep thought and several tests to pass a feasible check, but I envision big potential of these views to reinforce Source and Creator views, and to expand the search tools.

**Comment by zackkrida** [comment]
This iteration looks like a great place to begin work on this functionality. It's a pragmatic and attractive "minimum viable product" for these views and establishes a great baseline for the future enhancements you've already mentioned. 👍 from me. 

@WordPress/openverse-frontend could someone else review and approve these designs, as if it were a project proposal?

**Comment by sarayourfriend** [comment]
I am in agreement with Zack.

**Comment by zackkrida** [comment]
We've concluded these designs are ready for implementation! @fcoveram is going to share final assets here, close the issue, and update the project thread.

**Comment by fcoveram** [comment]
I updated the Figma file with the last changes and it is ready for development 🎉 

A few days ago, Figma introduced a new feature, [Dev Mode](https://www.figma.com/blog/introducing-dev-mode/). I started exploring the design features in the Design Library, and in this case, I applied spacing variables in all mockups.

## Design assets

[Here are](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?type=design&node-id=22%3A13656&mode=dev) the mockups in dev mode.

**Comment by AetherUnbound** [comment]
I'm late with this but wanted to say that these look _fantastic_ and I'm so excited for this feature! I'm also glad you were able to figure out a solution for the long creator names 😄
