### ISSUE TITLE
HTTP errors (415,424) in developer console

### ISSUE THREAD

**Issue by roytanck** [WordPress/openverse#2227]
## Description

When searching Openverse from WordPress 6.2.2, I'm seeing a lot of HTTP errors in the devtools console. This happens with thumbnail URLs like these:

https://api.openverse.engineering/v1/images/e1f5bd15-2ce1-4323-9088-684984f2d849/thumb/
https://api.openverse.engineering/v1/images/86578ecd-a9fb-4813-ac5c-dcb2a3e2ec52/thumb/
https://api.openverse.engineering/v1/images/4f1d53f7-0c48-4ae4-ac4e-57c3477aed1f/thumb/

This does not seem to have a functional impact. I can still see the thumbnails, and select the images. Colleagues report more serious errors after several searches, but I've not been able to recreate this.

## Reproduction

1. Create a new page or post.
2. Click the [+] button, then "media", then "Openverse".
3. Enter a seach keyword ("meerkat" yields a lot of 424's).
4. Check the console to see the errors.

## Screenshots

![Scherm­afbeelding 2023-05-30 om 10 35 04](https://github.com/WordPress/openverse/assets/1642390/e2a541fd-fe73-446c-9368-22ee28aaffbf)

## Environment

- Device: Macbook Pro (M1), Lenovo Thinkpad E490
- OS: MacOS 13.3.1, Windows 10, Ubuntu 20.04
- Browser: Chrome, Firefox
- Version: latest

**Comment by zackkrida** [comment]
Hi @roytanck, thanks again for reporting this. The issue was with one between Openverse's sources, rawpixel.com, and [photon](https://developer.wordpress.com/docs/photon/), the image service we're currently using to serve Openverse's thumbnails. Photon was incorrectly polluting rawpixel urls with extra query parameters and causing the results to fail.

I've tested this with several test searches in WP 6.2 and the latest nightly, and there are no longer any 424s present.

There _are_ still some 415s present in Openverse related to images from the Smithsonian which send chunked jpeg files that do not have the correct Content-Type headers set. I am going to create a separate issue for those now.
