### ISSUE TITLE
Redis at full memory capacity causing `ReadOnlyError` 

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#2383]
## Description

It seems the Redis cluster has no more room to write. We received the following message today:

> ConnectionInterrupted
>
> Redis ReadOnlyError: You can't write against a read only replica.

## Reproduction

N/A

## Screenshots

<figure>
<figcaption>Current items count for last week</figcaption><br>
<img width="562" alt="CleanShot 2023-06-12 at 10 29 43@2x" src="https://github.com/WordPress/openverse/assets/9145885/48937432-89aa-4bba-98a2-e6368786bc72">
</figure><br><br>

<figure>
<figcaption>Database Memory Usage Percentage for last week</figcaption><br>
<img width="559" alt="CleanShot 2023-06-12 at 10 29 20@2x" src="https://github.com/WordPress/openverse/assets/9145885/899001fd-ea87-44eb-bc38-f3d553aad434"><br>
</figure>

## Environment

Production cluster.

## Additional context

[Sentry context](https://openverse.sentry.io/share/issue/d4e17b0ac59d450186e5513002480ab5/).

**Comment by zackkrida** [comment]
Fixed by scaling vertically and increasing capacity from a M4.large node to a M4.xlarge node. 

Moving forward we'll need to audit what we're storing in redis, the expirys of these keys, and if any data should be moved to a more permanent storage place. We could also investigate and consider alternative architectures, like a cluster with multiple nodes, although I don't suspect there would be any benefit to doing that.
