### ISSUE TITLE
Delete previous project reminder comment before issuing a new one

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2836]
## Description

In #2251 we added logic for issuing a reminder to post an update in project threads that match our standard "open" states. This reminder bot does not delete existing project thread comments before posting a new one, which can leave multiple duplicate comments in a row if a prompt is not addressed. Example: https://github.com/WordPress/openverse/issues/2545

Similar to the [logic we have for the Playwright failure comments](https://github.com/WordPress/openverse/blob/bc84fa0448f6a60d73ad72d45dbc89a8ae93f2aa/.github/workflows/ci_cd.yml#L757-L766), we should also delete the existing comment calling for an update on a project thread before issuing a new one.

**Comment by sarayourfriend** [comment]
@AetherUnbound Can you share more about why this behaviour is undesirable or why it's high enough priority to work on now? It only happens in a very specific edge case and, frankly, it's one that I think we _should_ have documented in the project. It only happens if a project goes an entire month or more without any updates to the project thread. My understanding of why we do project thread updates in the first place would suggest to me that we actually want to be able to clearly see that there were no updates, but that a reminder did happen, to document that (a) there was some breakdown in priorities that caused us not to post an update to that project thread and (b) to add an extra prompt for the next project update to include the entire missed period, particularly including any explanation of why/if the project was stalled (which seems like the most common reason why we would miss a project updated).

Maybe there is a different way to approach this? I think it's actually valuable to have those multiple pings and considering the case where they happen is rare _but still significant_ just collapsing the reminders doesn't feel like a solution to me (not just because I'm sceptical that there's a problem with it to begin with, but also because it really does hide potentially important information).

**Comment by AetherUnbound** [comment]
@sarayourfriend thanks for your thoughts! I think I was erroneously conflating the urgency of this situation with feedback folks have provided in the past about the PR review request reminders. I was considering the use case for both situations to be the same, but I agree that seeing multiple update-request comments on a project thread _does_ provide useful information about a breakdown somewhere. An additional prompt on a second-in-a-row update request might be good, but is certainly not something that would require any urgency looking into. Multiple PR review reminders left in a PR _is_ noise, but it isn't for the project threads. I'll go ahead and close this issue then 🙂
