### ISSUE TITLE
Source and provider definitions in single result page

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#2840]
## Problem

The Additional search views' designs (#2113) update the metadata section in single result page to distinguish between source and providers, but mockups did not include the tooltip texts triggered by the new Metadata element design (#2582).

## Description

I'd like your thoughts in the following copy for the two tooltips:

* **Source:** Organization granting the content
* **Provider:** Site hosting the content

In context, this looks like this

https://github.com/WordPress/openverse/assets/895819/f5df206e-9bc6-4353-85e1-d326c2e194e4

Tooltip texts should remain short and clear, so ideally we should keep this sentence as simple as possible. Acknowledging that [sources page](https://openverse.org/sources) gives more detail about these two concepts.

What do you think of these texts?

**Comment by DanSoschin** [comment]
Some suggestions for the tooltips. It's not entirely clear to me what the difference is between "source" and "provider" because those two words could potentially be interchangeable. I think it might be helpful to mention the URL for more info in the tooltip. I would also suggest changing the word "provider" to "site", unless this has a broader/cascading effect on openverse. Site (as in website) seems to be a more clear definition of what this will be.

Source: 
(a) Organization that created or owns the original content. See [openverse.org/sources](http://openverse.org/sources) for more info.
(b) Original provider of the content. See [openverse.org/sources](http://openverse.org/sources) for more info.

Provider:
(a) Website where this content resides. See [openverse.org/sources](http://openverse.org/sources) for more info.

**Comment by rmartinezduque** [comment]
Building on some of the points you both mention, these are my recommendations:

- **Source:**
   a) Organization or institution that creates or shares the digital work.
   b) Entity that creates or shares the digital work.
- **Provider:** Website where the digital work is hosted.

I would suggest using `digital or creative work` for consistency with the homepage, but I think `content` works too.

**Comment by fcoveram** [comment]
Thanks @DanSoschin and @rmartinezduque for the suggestions.

I think we should go with the simplest solution: one sentence in a tooltip. See how people interact with it and add more content if needed.

Regarding texts and concepts
* Replacing "Provider" with "Site" has a significant impact on the product and requires deep review before applying the change. 
* Digital or creative work sounds good for consistency, but in all internal pages we talk about content. Homepage's heading belongs more to a marketing call rather than a site-wise concept.

---

For now, this PR addresses the helper text where the copy that matches perfectly is (a mix of both ideas):
* **Source:** Organization that created or owns the original content 
* **Provider:** Website where the content is hosted.

The [mockup](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?type=design&node-id=1449-59264&mode=design&t=EwmMDUBGTbxrYWRU-4) is part of Additional Search Views' [designs](https://www.figma.com/file/niWnCgB7K0Y4e4mgxMrnRC/Additional-search-views?type=design&node-id=22-13656&mode=design&t=EwmMDUBGTbxrYWRU-0), and the `hover` interaction should look like this

https://github.com/WordPress/openverse/assets/895819/76cc7559-5e8b-4bcd-a4f1-c4752d54252f
