### ISSUE TITLE
Handle  `SychronousOnlyOperation` exceptions

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#2861]
## Description

The conversion of the API to ASGI raises [`SychronousOnlyOperation` exceptions](https://openverse.sentry.io/issues/?project=6107216&query=synchronousonlyoperation) in Sentry. This should be resolved or appropriately handled.

**Comment by sarayourfriend** [comment]
This was due to a bad deployment of a production image that did not include the underlying changes required to use `gunicorn` from the baked-in run command. It actually doesn't have anything to do with the ASGI conversion generally, fortunately. Only be consequence of my error in deploying it. The Sentry issue was resolved once the deployment was reversed.

Related to #2785
