### ISSUE TITLE
Unify formatting rules across languages

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#287]
## Problem

We format Python to use double quotes for strings and JavaScript to use single quotes for strings. Let's choose one and apply it to both languages.

## Description

I don't know what the argument is for using single quotes other than it being slightly easier to type. I do know that the argument against defaulting to them is that it's far more common to write a string with an apostrophe that would then need to be escaped or the string then be an odd ball and use double quotes, than to include a double quote inside a string.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
Double quotes universally sounds good 👍

**Comment by AetherUnbound** [comment]
+1 on double quotes, especially since our very opinionated Python code formatter `black` [enforces double quotes](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings). Their rationale is similar:

> Why settle on double quotes? They anticipate apostrophes in English text. They match the docstring standard described in [PEP 257](https://www.python.org/dev/peps/pep-0257/#what-is-a-docstring). An empty string in double quotes ("") is impossible to confuse with a one double-quote regardless of fonts and syntax highlighting used. On top of this, double quotes for strings are consistent with C which Python interacts a lot with.

They do provide an option to skip string normalization altogether, but that might lead us to a place where we have a mix of single and double quotes.
