### ISSUE TITLE
Wait to change all ES aliases until filtered index creation is complete

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#2981]
## Problem

Presently, the primary media index alias is changed from the old index to the new one during a data refresh _before_ the filtered index creation has run. This means that both the reindex initiated by the filtered index DAG _and_ the production API are working against the same index. We believe that this may be impacting production performance (see #2975).

## Description

It may be best to wait until the filtered index creation is complete to change the primary media alias. This would prevent the API from using an index which is also being used as the source of a reindex vis-a-vis the creation of the filtered index. The goal with this change would be to allow a higher throttle & throughput of the filtered index creation without affecting the API.

I believe this could be done by bringing the filtered index creation steps into the media refresh DAGs (currently they exist as a separate, triggered DAG). This could actually make orchestration _easier_ since it would mean that we could remove the "check filtered index creation" step. That would remove our ability to trigger the filtered index creation on its own however, so perhaps it might be better to add a step to the primary DAG wait for the triggered index DAG to complete. This may require some changes to the logic that checks for running DAGs, since the data refresh itself will be running until the filtered index creation step completes.

## Additional context

This came up alongside, but is not directly related to, #2980

**Comment by sarayourfriend** [comment]
The filtered index DAG factory could be refactored to only return the "inner tasks", so that the data refresh DAG can include those tasks directly (instead of dispatching the standalone DAG) and the standalone DAG can incorporate the inner tasks after doing the concurrency check.

I don't know if that approach would reduce the complexity for implementing this issue or if it's indeed easier for the data refresh DAG to keep a sensor to wait for the standalone DAG's completion before promoting the aliases. One thing to consider is whether one approach or the other is easier from an error handling perspective (something I'm not familiar enough with Airflow to guess at). @stacimc and @AetherUnbound, are either of y'all able to share a hunch of which would be the easiest approach to manage?

**Comment by AetherUnbound** [comment]
I think there are a few options we could use:
- A combination [`TriggerDagRun`](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html) operator and [`ExternalTaskSensor`](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/sensors/external_task/index.html) pair, which would trigger the DAG and wait for it to finish
- Using a [SubDag](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#subdags) for managing the tasks. IIRC the Airflow community recommends _against_ this because they don't respect parallelism and require the DAGs have a schedule (they may also be deprecated, the docs don't seem to specify).
- Use a `TaskGroup` as you mention @sarayourfriend, where the inner tasks for the DAG are entirely defined within the task group. That group could then be used within the data refresh DAG by calling the function to generate it. This seems to [have some advantages over a subdag](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html#taskgroups-vs-subdags).

I think the `TaskGroup`/inner task option might be best, given the concurrency checks we run at the beginning of the DAG can either be made specific only to the stand-alone DAG or they're not too complicated to adapt to the new setup!
