### ISSUE TITLE
Filter dead link-only providers in the Catalog

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#3257]
## Problem

The search controller includes a filter to [dynamically exclude providers](https://github.com/WordPress/openverse/blob/main/api/api/controllers/search_controller.py#L279) with the `filter_content` attribute set. This allows us to exclude providers whose content is exclusively dead links, but it results in an additional ES filter on every query.

## Description

We could instead filter out these providers on the Catalog side by removing them from the Catalog's media tables. On subsequent data refreshes, the records will no longer be copied into the API tables -- no filtering necessary. This makes this a one-time operation.

Rather than simply deleting the records, we should move them into a new table. For now, these tables should be as simple as possible. This will be `deleted_image` and `deleted_audio`. They should be exact copies of the `image` and `audio` tables respectively, with two new columns:
* `deleted_on`: timestamp for when the record was added to the table/deleted from the corresponding media table
* `reason`: reason the record was deleted, which for the purposes of this work will just be `dead_link` for all records

In the future, there may be a project to consider other cases for handling deleted media in the Catalog. The deleted media tables may be changed as part of that work. The goal in this issue is to make something simple that can easily be modified when the project is planned more thoroughly (for that reason, for example, we'll just preserve every column from the media tables exactly so that the records could be easily restored).b 

We'll need to:
* Create the tables
* Write queries for moving the archived provider records into these tables, and then deleting them from the main media tables. It might make the most sense to do this in a small DAG.
* Remove the filtering from the API

## Alternatives

Alternatively this could be implemented more quickly by updating the ingestion server to [filter out these records](https://github.com/WordPress/openverse/blob/main/ingestion_server/ingestion_server/queries.py#L178) during the copy_data query step so that they are not copied into the API tables. This would be a very small change, and is similar to how we already filter out records that are in the API's `DeletedMedia` table.

The primary disadvantage is that this filtering needs to happen on every data refresh. I am not certain how much longer the

**Comment by stacimc** [comment]
In an ad-hoc discussion, @obulat and I agreed that the approach described in this issue (moving the records into a deleted media table in the Catalog) would be the better solution. However as I've written up this issue it's occurred to me how much quicker the ingestion-server approach would be to implement, so I think it's worth touching base again to make sure this is still how we want to proceed. Another option is to do the filtering in the ingestion server _temporarily_, as it would also be easy to undo. For the moment I'll take a time-boxed approach into looking at both options.

**Comment by obulat** [comment]
Update: the image refresh has finished running on November 18th, and there all of the media from these providers has been removed from the API database and the ES indices. We can now delete these providers from the 

For the record, I'll leave a list of providers and notes on them. Note that this data was parsed from the HTML pages in the CommonCrawl archives. Since then, either their URL structures have changed, or the site has been completely removed.

## Removed providers

### To be removed completely
- iha.com. This was a vacation rentals website that shared the photos with a CC license. This site is completely closed now.
- 500px removed licensing under Creative commons.

### Can be re-added using API

- Behance: #1786
- Deviantart: #1758

### Can be re-added using other ingestion methods
- Mccord Stewart Museum: no API, but it could be possible to scrape using advanced search for public domain and "image available": https://collections.musee-mccord-stewart.ca/en/advancedsearch/Objects/collections%3APublic%20Domain%3BmediaExistence%3Atrue
- Thorvaldsens museum. Does not have an API, and there seems to be no way of filtering out only the openly-licensed images on the site. An example of a CC0 image: https://kataloget.thorvaldsensmuseum.dk/AX64.
