### ISSUE TITLE
Run Prettier on Markdown files

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#333]
## Problem

We're currently excluding Markdown files from being formatted by Prettier. Prettier follows a style for Markdown that's very different from our own and can lead to large-scale changes in existing documents, both in this repo and the repos that sync the lint rules from it.

See @krysal's comment: https://github.com/WordPress/openverse/pull/332#discussion_r1024552892
      
## Description

We need to see what changes Prettier makes and whether the added consistency is worth having (I would suggest it is).

Some notable changes I recall is
- lots of blank lines will be added (one after every heading)
- <s>Prettier uses `*` for bullets so lots of changes there.</s> Prettier uses `-` (thanks @zackkrida) but even that leads of lots of changes because some of our files use `*`.

## Alternatives

Since Markdown is very free-form we can exclude it from Prettier and let folks write their documents in whatever way suits them.

## Votes

Please update this section if you have an opinion.

- For Prettier on Markdown: @dhruvkb, @zackkrida 
- Against Prettier for Markdown:

**Comment by zackkrida** [comment]
Prettier actually uses hyphens for bullets, they switched in 2018 iirc. I just tested and this:

```md
# Prettier
* This is what it looks like before
* This is what it looks like before too
```


```md
# Prettier

- This is what it looks like before
- This is what it looks like before too
```

I would actually prefer that we _do_ lint markdown files with Prettier to avoid inconsistencies. Particularly the manual wrapping of lines to an arbitrary character length, which is something that's happening in a few of our repos. I vastly prefer readers setting their desired line length with word wrap in their IDEs or text editor.

**Comment by sarayourfriend** [comment]
I'm going to work on adding prettier to format Markdown so that we get the line-length benefits needed to make discussions on Markdown documents a little smoother. I _think_ we should accept the Prettier changes to the Markdown, even if we don't like a lot of them. The reason being is that prettier automatically re-writes things, so the writer, ideally, doesn't even really need to worry about the rules when they're writing them.

We could try to use a tool like MarkdownLint (https://github.com/markdownlint/markdownlint), but it does not auto-fix issues, so would be a huge pain for writers who would need to manually adjust things like line length.
