### ISSUE TITLE
Related query does not use filtered index

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3348]
## Description

@stacimc and I were looking at index memory usage after the production ASGI changes (which included the related query improvements from #3151), and noticed a difference in memory usage of the filtered and unfiltered image indexes. The graphs showed the filtered index query cache memory increasing after the deployment and the unfiltered index query cache memory decreasing. This made us wonder if the changes to the related query unintentionally included a change to the index queried for the related changes. The PR does not change which index we use for the related query. But we did notice that we're using the unfiltered index for related, rather than the filtered index.

The index used for related media is passed to the related media function by the view. `MediaViewSet::related` passes the default index set on the media view set implementation:

https://github.com/WordPress/openverse/blob/6f6aac3e013eef1c10d1b9fc1d089eb589363ce3/api/api/views/media_views.py#L162-L166

For images and audio, this is both the `image` and `audio` index names, which are the aliases used for the unfiltered indices.

The `related_media` function passes this directly to `Search`, meaning it queries the unfiltered index. To make things a bit clearer, we should change the `related_media` function to accept the _media type_ as a parameter, and then always query the filtered index for the media type. Pass the media type to make it clear that the index is chosen by the `related_media` function and is always the filtered index for the media type. Then use the filtered index when constructing `Search`, for example, `search = Search(index=f"{media_type}-filtered")`.

**Comment by obulat** [comment]
In the related endpoint, we use 2 ES requests: the first one to get the item with the requested identifier to get its title, tags and creator, and the second one to get related items based on that data. The second request does use the filtered index.
However, for the first request, we **have** to use the original index because the main item could be a sensitive one not available in the filtered index. In fact, when we pointed both indexes to the filtered index, we got several 500 errors because the first request could not find the item that was in the non-filtered index (the issue for turning these errors into 404 is forthcoming).
If we used the database to get the item instead of ES, would it be more performant and use less memory, @sarayourfriend ?

**Comment by sarayourfriend** [comment]
Oh! I totally misread the code. _Never mind_, this ticket is invalid as is. I might open a PR to add some comments to help easy skimming of the related media function, but there's nothing to do here. Thanks for clarifying how the function works.

**Comment by sarayourfriend** [comment]
> If we used the database to get the item instead of ES, would it be more performant and use less memory, @sarayourfriend ?

For posterity, I don't think there's an easy way to measure this, and I'm sceptical a request to one or the other would matter too much either way. If we want to overall reduce the number of queries to ES, then that's a potentially meaningful way of thinking about the optimisation, because theoretically those requests for individual items are tying up threads that could serve a search request, but our actual search throughput doesn't appear to be an issue as long as our queries are working well. I'd say we shouldn't make a change in that regard unless we have a confident way to measure the effect of it.
