### ISSUE TITLE
Audit: `shed` for complete Python linting

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#335]
## Problem

Currently we use the following tools for linting Python code:
- Black
- isort
- Flake8
- pyupgrade

Each of these tools has their own configurations, options and opinions.

## Description

@AetherUnbound proposed `shed` ([GitHub](https://github.com/Zac-HD/shed)) that wraps all these tools, is completely opinionated and replaces all these tools in our pre-commit with a single hook. This would lead to simpler config and less configuration.

But `shed` has some opinions that differ from our current ones that can lead to a pretty big diff. So the goal is to audit how much of a change `shed` will cause and if it's worth the trouble in return for a simpler config and more opinionated linter.

## Alternatives

We continue to roll our own Python lint system with separate single-utility tools that we can configure to our liking.

## Additional context

Compared to the tools we currently use, which are very standardised and highly-rated, `shed` is new, not used that much and isn't under the umbrella of any of the major Python organisations. It might also be a factor to consider when making a call.

**Comment by sarayourfriend** [comment]
I've run shed locally and collected some notes of things that annoyed me, to varying levels of annoyance. They're all nitpicks I could personally live with (mostly because they're automated, _sort of_) but do find annoying nonetheless:

1. Removes unused imports. We use these in `__init__` modules sometimes and it is truly a pain to add `noqa` to all of these lines and to have to re-add the import and add `noqa` when the import is automatically removed during `pre-commit` linting.
2. It does not ignore Django migrations. This is mostly just annoying and useless noise, imo, that will ring up every time in pre-commit when you add a new migration.
3. It removes the double blank line whitespace after imports. I personally like this convention as it makes it easier to navigate a module that has lots of imports. I'm a big fan of whitespace though, but I know it annoys others as it makes code take up more vertical and horizontal space. Both arguments are in favour of readability, just with different ideas of what is best for readability. My preference is to continue what we are currently doing (which I also think is the general approach of most Python projects) but again, mostly an annoyance.
4. We tend to organise django and rest_framework imports separate from other library imports (and separate from stdlib imports). We have a similar convention that is actually enforced by our linter in the Nuxt codebase. `shed` undos all of these and puts django and rest_framework imports mixed in with the other third party libraries.

I actually do like the unused import/variable deletion, but I wish it skip it for `__init__` modules.

Some of the diff is also changing from single to double quotes, which I proposed doing in https://github.com/WordPress/openverse/issues/287 but forgot to follow up on.

**Comment by dhruvkb** [comment]
After the monorepo plans, I've been more skeptical of using `shed`. The main benefit it adds (simplifying the `pre-commit-config.yaml` file) is a one-off (that pays even less in a monorepo-style setting) but the implications of using it might be long-term.

**Comment by dhruvkb** [comment]
This is related to #787 which discusses using Ruff.

**Comment by dhruvkb** [comment]
Closing this as we've gone with Ruff, tracked in #787.
