### ISSUE TITLE
No labels are applied if labelling workflow fails

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#338]
## Description

If the workflow for labelling new PRs (https://github.com/WordPress/openverse/blob/083f196cf10cc24f95e43b767b47304cf748dc68/.github/workflows/label_new_pr.yml) fails, no labels are applied to the PR at all, which also prevents the workflow to check labels from being triggered. Such PRs will be left unlabelled and will not show up in the awaiting triage list.

## Solution

If the workflow fails, the "🚦 status: awaiting triage" label should be applied.

**Comment by rohitm02** [comment]
Hi, this is my first attempt at contributing to open-source. I would like some clarity regarding the issue and also would like to know the prerequisites. Thank you

**Comment by AetherUnbound** [comment]
Hi @rohitm02! We'd love to have you work on this 🙂 Presently, we have a workflow (https://github.com/WordPress/openverse/blob/083f196cf10cc24f95e43b767b47304cf748dc68/.github/workflows/label_pr.yml) that will attempt to label a PR based off a few heuristics. The above linked workflow is actually a dispatcher from our individual repos (e.g. the [catalog repo](https://github.com/WordPress/openverse-catalog)) which kicks off the `label_pr` workflow to run in this repo.

I believe what @dhruvkb is describing in this issue is that sometimes, if the `label_pr` workflow in this repo fails, the PR it was triggered from never gets _any_ labels. Our label check only runs if there are labels on a PR, so because no labels were added those checks don't run and we're left with an entirely unlabeled (but technically mergeable) PR.

One way we could address this is add an extra step in the `label_pr` workflow which runs if the [label PR step](https://github.com/WordPress/openverse/blob/083f196cf10cc24f95e43b767b47304cf748dc68/.github/workflows/label_pr.yml#L35-L37) fails. GitHub provides a mechanism for performing such a check, see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-status-check-functions. We could use a simple action like the [`add-labels`](https://github.com/marketplace/actions/actions-ecosystem-add-labels) action in the next step with this `if: ${{ failure() }}` check to unconditionally add the ":vertical_traffic_light: status: awaiting triage" label to the PR in question if the prior step fails.

Hope that helps! If you're looking for more general information about how to contribute, please see our [CONTRIBUTING.md](https://github.com/WordPress/openverse/blob/main/CONTRIBUTING.md). If you have specific questions about this issue though, feel free to add them here 😄

**Comment by vortex73** [comment]
Hey Guys! Just in case this issue is still not taken, this is potentially my first contribution. So could anybody point me to what technologies i would need to learn to understand this issue to its full capacity? I have pretty fair experience with python and cpp and open to learning anything new.
Thanks!

**Comment by zackkrida** [comment]
Hi @vortex73 did you see the description provided by @AetherUnbound in [this comment](https://github.com/WordPress/openverse/issues/338#issuecomment-1369986526)? This issue relates to a GitHub workflow, so requires working with GitHub workflows and yaml files. In her comment Madison left some documentation and resources. 

We're happy to answer any additional questions as you look into this issue more, thanks!

**Comment by vortex73** [comment]
I've almost understood everything in this issue. Could you please provide me with steps on how to reproduce this issue if there is any noticeable pattern?

**Comment by vortex73** [comment]
Also Could you provide me with a dummy example of what the function `get_linked_issue`  returns
https://github.com/WordPress/openverse/blob/083f196cf10cc24f95e43b767b47304cf748dc68/automations/python/label_pr.py#L107-L133

Thanks!

**Comment by AetherUnbound** [comment]
Hi @vortex73! What I'm proposing is actually an additional step _outside_ of the `label_pr.py` script. This would be a step that follows it in the [`label_pr` GitHub Action](https://github.com/WordPress/openverse/blob/083f196cf10cc24f95e43b767b47304cf748dc68/.github/workflows/label_pr.yml) that is only run on failure (as described in my comment above). I also suggest an action that could be used, namely: [`actions-ecosystem/action-add-labels`](https://github.com/marketplace/actions/actions-ecosystem-add-labels).

So essentially this would all be done in the GitHub Actions definition rather than in Python. Here's a link to GitHub's extensive documentation on actions: https://docs.github.com/en/actions

Hopefully this helps, let us know if there's anything that needs additional clarification 🙂

**Comment by vortex73** [comment]
Thanks @AetherUnbound . I'm almost done with the additions. But the modified code is not passing one of the checks(Lint) on the repository. 

    An unexpected error has occurred: CalledProcessError: command: ('/home/runner/.cache/pre-commit/repo2qm6glpr/py_env-python3/bin/python', '-mpip', 'install', '.')
    return code: 1
    expected return code: 0
    stdout:
        Processing /home/runner/.cache/pre-commit/repo2qm6glpr
          Installing build dependencies: started
          Installing build dependencies: finished with status 'done'
          Getting requirements to build wheel: started
          Getting requirements to build wheel: finished with status 'done'
          Preparing metadata (pyproject.toml): started
          Preparing metadata (pyproject.toml): finished with status 'error'
    stderr:
          error: subprocess-exited-with-error
          
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [14 lines of output]
          Traceback (most recent call last):
            File "/home/runner/.cache/pre-commit/repo2qm6glpr/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
              main()
            File "/home/runner/.cache/pre-commit/repo2qm6glpr/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/home/runner/.cache/pre-commit/repo2qm6glpr/py_env-python3/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-4_5682l3/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-4_5682l3/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
    Check the log at /home/runner/.cache/pre-commit/pre-commit.log
    error: Recipe `lint` failed on line 23 with exit code 3
    Error: Process completed with exit code 3.

**Comment by AetherUnbound** [comment]
Ah, this was unfortunately due to #367 I believe! I think if you rebase your changes onto `origin/main`, they should now pass the lint checks 🙂
