### ISSUE TITLE
Skip `needs_db` and always map ES hits to DB results

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#3436]
## Problem

Currently the serializers and request params can opt-in and out of mapping ES hits to DB results using the `needs_db` param. This was added when the DB mapping was introduced as a way to test the functionality's viability and peformance impact (although it was not used as such).

## Description

Now that our indices are leaner and contain no info beyond what's indexed and searchable the flag is almost always set to `True` and hence does not need to exist at all. Remove all occurrences of `needs_db` and replace it with a code branch that is always active.

This will simplify a lot of logic and clarify that there is only one path taken by the API from ES hits to JSON response.

**Comment by ngken0995** [comment]
@dhruvkb `test_auth.py`([link](https://github.com/WordPress/openverse/blob/c2b9750c26581990c0e8607c26a114b402384fa3/api/test/test_auth.py#L213)) and `test_dead_link_filter`([link](https://github.com/WordPress/openverse/blob/c2b9750c26581990c0e8607c26a114b402384fa3/api/test/test_dead_link_filter.py#L14)) use needs_db to prevent DB lookup for ES results because DB is empty. Even though if I set all needs_db to `True` or remove all `needs_db` the test will fail.

**Comment by dhruvkb** [comment]
In those tests, we should mock the DB request so that data we expect is provided to the tests. Ideally we should not be basing our code around tests, but the other way around, so if those tests fail due to this change, we need to find a way to correct the tests instead.

**Comment by ngken0995** [comment]
> In those tests, we should mock the DB request so that data we expect is provided to the tests.

There is a function which might be called for DB request: `get_db_results`. I could use monkeypatch.setattr for `get_db_result` and return a expected value. Then `get_media_results` return the correct data. How can I retrieve the expected data?

**Comment by ngken0995** [comment]
@dhruvkb ^

**Comment by dhruvkb** [comment]
One way would be to attach a debugger when it calls the DB and see the value. In most cases, I get lazy and just `print` to `STDOUT`/write to a file if I need to check some value during runtime.
