### ISSUE TITLE
More visual disctintion to loading bar

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#3497]
## Problem

With my current browser's dark theme, the loading bar on top of the page is very subtle and not very distinguishable. See the video below.

https://github.com/WordPress/openverse/assets/895819/cfec2fc4-47f1-4c13-9850-0e5a6e3c31ed

This browser setting is personal and, as far as I know, there is no way of knowing which color predominates in the theme set.

## Description

We can try changing the bar color to `pink (#C52B9B)` as it works well next to light and dark colors, tones that come by default in browsers' light and dark modes.

**Comment by sarayourfriend** [comment]
@fcoveram do you still see this bar? I think it might be a browser feature, rather than part of the website. I don't see it in Firefox. Maybe there are ways of controlling the colour of this, but I'm not sure... or maybe it was lost in the Nuxt 3 conversion?

I guess this might also be affected by #3592?

**Comment by fcoveram** [comment]
You are right 🤯 I no longer see it. I switched to Arc browser and before was on Firefox. But if you also don't see it perhaps was an add-on I had installed.

**Comment by sarayourfriend** [comment]
I recall seeing this on a variety of websites in Firefox, but couldn't get it to come up again when I tried. Maybe it's a Firefox feature that changed.

I'll close as won't fix and we can revisit this again if it comes up again. Thanks!
