### ISSUE TITLE
Add content moderator user preferences admin view

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3634]
## Description

See the following for implementation description and rationale: https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#add-user-preferences-admin-view

**Comment by AetherUnbound** [comment]
It seems like we have two options here [as described by the Django documentation](https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#extending-user):
1. Add a "profile" class with a `OneToOneField` on the `User` model
2. Swapping out the entire model for a different, subclassed `User` model

My preference on this is the first option, because Django describes that doing the second as [quite difficult mid-project](https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project). I'm going to go ahead and pursue the first, but if anyone has concerns/objections please voice them.

**Comment by sarayourfriend** [comment]
Good call, thanks for looking deeper into that, Madison.
