### ISSUE TITLE
Use a persistent cache for tldextract across CI runs

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#3716]
## Current Situation

tldextract is a library used by the ingestion server to help extract TLDs (not a surprise, based on the library's name!).

It relies on updated public suffix information, which it requests the first time it runs. This information is cached, and we should persist it accross test runs.

## Suggested Improvement

Configure [tldextract's cache location](https://pypi.org/project/tldextract/) to a place we can easily cache in GitHub Actions. Use `tldextract --update` with the configured cache location, as shown in the library docs, to update the cached data as needed, and prevent unnecessary network requests in tests.

## Benefit

Prevent unnecessary network requests during test runs.

**Comment by sarayourfriend** [comment]
@krysal @stacimc will the ingestion worker still have this dependency? I was wondering whether this is no longer needed since we moved URL clean up out of the data refresh in #430?

**Comment by AetherUnbound** [comment]
It does still have that dependency, although I do not believe it will be carried forward once we have the new indexer workers running. We should be able to close this issue.

**Comment by stacimc** [comment]
The indexer worker definitely will not have this dependency. I will leave it to @obulat to confirm if it needed elsewhere/where the cleanup is happening as I'm not sure 😅

**Comment by stacimc** [comment]
@AetherUnbound does the catalog's usage of tldextract not affect this?

**Comment by AetherUnbound** [comment]
@stacimc Because of the [`pytest-socket` plugin we use](https://github.com/WordPress/openverse/blob/1f28543523cb406f06b20855498307399cbcce13/catalog/pytest.ini#L10-L13) and the [example overrides we have for testing](https://github.com/WordPress/openverse/blob/59a3a3f73e38795cc3630e2cbb9b16e01b0a9dcd/catalog/tests/dags/common/test_urls.py#L15-L16), `tldextract` does not make any outgoing requests during the catalog's testing and any caching it does is likely insignificant and not worth the effort to attempt to cache (IMO)!
