### ISSUE TITLE
Replace hard-coded pnpm version with the value from package.json

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#409]
## Problem

The pnpm version is hard-coded in the workflows. Keeping it updated manually will be tedious. 

## Description

We can, instead, get it from the `package.json` as in the frontend repository's Playwright Docker setup:

https://github.com/WordPress/openverse-frontend/blob/3baca4c90b1f3912bbd8058fb316e416d522a94a/Dockerfile.playwright#L6

**Comment by krysal** [comment]
@obulat Could you specify which are the workflows affected?

**Comment by gsoria** [comment]
@obulat Could you please confirm where the hardcoded version in the workflow that you are referring to is? I'm wondering if you meant to explicitly define pnpm version in the [frontend Dockerfile](https://github.com/WordPress/openverse/blob/main/frontend/Dockerfile#L9).

**Comment by obulat** [comment]
I should have added a link when creating the issue...
I think @dhruvkb has updated the Dockerfile that had a hard-coded pnpm version. As for the frontend Dockerfile, I am not sure why there is no pnpm version there.

**Comment by dhruvkb** [comment]
I think the original issue no longer applies. The reason we had hardcoded the pnpm version in the workflows was because the package.json file was in a subfolder.

The [`pnpm` setup action](https://github.com/pnpm/action-setup) is capable of [automatically determining and setting up](https://github.com/pnpm/action-setup#version) the right version of `pnpm` if there is a root `package.json` file with the `packageManager` field set. Since we moved to a monorepo, that is indeed the case and so we no longer hardcode the pnpm version in our workflows.
