### ISSUE TITLE
Site theme switcher (dark mode toggle)

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#4155]
Designs for Dark mode project (#3592)

## Description
Given that users need to set the site theme from any part of the site, the most affordable area is the site footer. It already has the language selector, that behaves equally, and adding the action there is the more logical solution.

## Mockups
For the current arrangement of pages in both footer content and internal, the following version is the one that convince me most.

![New footer design in XS and LG breakpoints](https://github.com/WordPress/openverse/assets/895819/4373c032-813d-4aeb-81c3-c2db43d23e83)

The switcher is placed next to the language selector and it behaves equally. The options displayed are Light, Dark, and System in the OS/browser popover.

### Footer 
Content footer is on top and internal footer at the bottom.

![Content and internal footers](https://github.com/WordPress/openverse/assets/895819/3e7954eb-11f3-4f13-ad7a-c4c4b8adf48c)

## Middle- and long-term idea
With the [design explored](https://github.com/WordPress/openverse/issues/3564#issuecomment-1916380597) (#3564) to make the internal pages area more simple, I would like to bring again the opportunity we have to make the footer even more simple by putting the general/site settings in a unique config menu.

![Designs for the future footer](https://github.com/WordPress/openverse/assets/895819/c8c63624-5935-4ad5-8668-d94a69aaabae)

![Site settings menu in XS and LG breakpoints](https://github.com/WordPress/openverse/assets/895819/97020796-52ee-4dca-894d-3eb256b34a43)

The benefits of this idea is twofold:
* It puts Openverse in a better position with regards to privacy by making the toggle more visible
* It's the first step towards placing settings in a single menu once user profile-related actions are needed in future features.

I personally would like to consider the implementation of this middle/long-term component. What do you think?

**Comment by jasmussen** [comment]
Generally looks good! Location seems good.

The border around the dropdown button makes it feel at home next to the language dropdown. But this button up here only has that same border type on hover:

![Screenshot 2024-04-18 at 15 13 54](https://github.com/WordPress/openverse/assets/1204802/534abc4d-ede9-473f-862a-32b8411efb69)

Is there some heuristic we can apply for when the dropdown button is outlined vs. not? _Optical balance_ can be fine, but just noting the opportunity.

Entirely separate observations:

* The dropdown chevrons feel a bit chunky and big to me, and the space between icon or label and chevron is a bit bigger than it might need to be. This is a bit more visible with the cog icon addition.
* In the block editor core project, we put toggles on the left of the label, as opposed to the right. I'm aware that toggles on the right is a relatively common practice especially in mobile, and I think it can work, but in the core project we had to move them to the left in part because under the hood it's a re-skinned checkbox, and those are usually preceding the label.

**Comment by jasmussen** [comment]
Oh, and I quite like the dark mode switcher on [Rich's site](https://rich.blog). I don't know that it entirely works for Openverse, but it's fun.

**Comment by AetherUnbound** [comment]
I think I'd advocate for the mid/long-term solution myself too! I think, as you say, puts us in a better position going forward for anything else we'd like users to be able to configure. Both designs look excellent though!

**Comment by zackkrida** [comment]
I'd personally like to start with the theme switcher directly in the footer. Since we plan to keep light mode enabled by default I think making the element prominent in the footer makes the feature more discoverable.

It also keeps the scope of the dark mode project smaller, as the new "settings" panel feels like a larger change that we may want to consider more carefully and/or spin into its own dedicated project to answer questions like "How does it scale if we have 4 more settings?", etc.

**Comment by fcoveram** [comment]
True. Let's keep it simple and go with the basic version. I will update the design file and come back once assets are ready for dev.

**Comment by fcoveram** [comment]
[Mockups are ready for dev](https://www.figma.com/file/OP3r0AJWo1k7U3K2hgRwwK/Dark-mode?type=design&node-id=1947-53334&mode=dev). Since the change involves mostly changes in components, I requested them in #4232
