### ISSUE TITLE
Onboarding CC Search users

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#42]
We need to consider how to properly onboard previous CC Search users, especially those who will visit Openverse for the first time via redirection, from search.creativecommons.org to wp.org/openverse

We should display a 'CC Search is now Openverse' message to these users. We need to make a few decisions about this:

- How intrusive should it be? A full-screen, centered modal, a top bar banner, a floating toast notification?
- Decide on final copy
- Decide on the message: what are we trying to tell them? That the project is still active, that it has the same vision and plan, etc.

## Technical details

We will look at the referrer to conditionally display this interface element to the user.

**Comment by panchovm** [comment]
Here is an idea with two graphic solutions.

A top-aligned message showing the new name, belonging to WP as an open source project, and a link to the [WP announcement](https://wordpress.org/news/2021/05/welcome-to-openverse/). 

Ignore the main WP header style since it is based on the News redesign and it might change.

## Solid and gradient dots background

![Home  dots background message](https://user-images.githubusercontent.com/895819/130512488-3b454087-8afd-4daf-bcb1-b26e4af337dd.png)

## Yellow gradient background

![Home  gradient background message](https://user-images.githubusercontent.com/895819/130512503-0d841885-06a6-4ff4-adc8-ac3650cece23.png)

**Comment by panchovm** [comment]
I have noticed that most acquisition announcements can't be closed but are visible for a few weeks before disappearing.

**Comment by zackkrida** [comment]
I'm fine with that too.

**Comment by panchovm** [comment]
Here is [the mockup](https://www.figma.com/file/BlUTIXRHLOq5mRITpDpi3E/Transitional-styles?node-id=3%3A185) of the onboarding message. Ready for implementation

**Comment by zackkrida** [comment]
Implemented in WordPress/openverse-frontend#212
