### ISSUE TITLE
Move "by" tag contains filter to tag exact match filter

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#4464]
## Description

Looking over our transformations, it seems we have two separate tag filtering steps that happen on the `MediaStore` class: [full string matching](https://github.com/WordPress/openverse/blob/d500b7764c411f7d228ae12c57dce519c8709610/catalog/dags/common/storage/media.py#L14-L15) and [substring matching](https://github.com/WordPress/openverse/blob/d500b7764c411f7d228ae12c57dce519c8709610/catalog/dags/common/storage/media.py#L21-L22). The latter case, however, has the value `by` as a substring match option. Whereas all of the other options feel fairly unique and pointed, the value `by` could be part of _so many_ valid tag possibilities that it seems like it should be part of the full string matching instead. Examples being: "by the sea", "colby jack", "byte array", etc.

We should move this value from `TAG_CONTAINS_DENYLIST` to `TAG_DENYLIST` in this file:

https://github.com/WordPress/openverse/blob/d500b7764c411f7d228ae12c57dce519c8709610/catalog/dags/common/storage/media.py#L15-L37

**Comment by sarayourfriend** [comment]
:+1: to `by` should be a full-tag match, maybe `cc by` (etc for the other CC license terms) as well.

In line with the discussion of #4417 and into https://github.com/WordPress/openverse/issues/4456, if we will soon have the ability to filter tags later in our data lifecycle, it'd be great to not do _any_ kind of wholesale exclusion of tags at this point.

My understanding of some of the requirements of https://github.com/WordPress/openverse/issues/4456, in line with the requirements of https://github.com/WordPress/openverse/pull/4417 not to include certain tags in search but keep them in our data, would lead me to think that excluding these tags at all is against that trend? I suppose I'm making an assumption about how those discussions will play out.

If we move this later on, though, we'll have greater flexibility to play with what tags we use for search, without precluding the possibility of tags not directly used in search still being useful. Perhaps the existence of some of these tags, even if they aren't part of the searched text, is a useful indicator of some quality of the work that would be relevant for some subset of searches (if not all searches).

If the task for this issue is just to move this check into the other set, fine for now, but perhaps an additional issue would be good to also stop throwing these tags away at ingestion time (if that's how they're being excluded).

**Comment by krysal** [comment]
> If the task for this issue is just to move this check into the other set, fine for now, but perhaps an additional issue would be good to also stop throwing these tags away at ingestion time (if that's how they're being excluded).

I was about to ask exactly this because, from sync discussions, I had understood that we wanted to preserve tags with low accuracy and move forward with cleaning deny-listed tags in the catalog since [we're already excluding them in new records](https://github.com/WordPress/openverse/blob/d500b7764c411f7d228ae12c57dce519c8709610/catalog/dags/common/storage/media.py#L299). Hence, I created #4453 (blocked while this is clarified). If the desire is to keep everything, then #4453 would not be necessary.

**Comment by sarayourfriend** [comment]
We are moving towards that, I assume Madison opened this issue as something we can resolve as a separate problem, rather than also solving it in that issue (or waiting to solve it after that issue).

As things are, we are incorrectly excluding the types of tags Madison mentioned in the issue. Why block this on overall changes?

**Comment by krysal** [comment]
> We are moving towards that...

Perfect, that is all the confirmation I needed. Thanks! 

> As things are, we are incorrectly excluding the types of tags Madison mentioned in the issue. Why block this on overall changes?
 
I wasn't referring to blocking _this_ issue (#4464) but #4453, which is unnecessary, so it's closed now. Sorry for the misunderstanding. I agree with moving the `by` tag 👍

**Comment by szymon-polaczy** [comment]
I'd like to work on this

**Comment by AetherUnbound** [comment]
Thanks @sarayourfriend and @krysal for piping in - yes, I agree that we should stop filtering tags at ingestion in the future once we move the filtering out of the ingestion server (see #4524). I'll make an issue for follow-up!
