### ISSUE TITLE
Airflow should support dark mode

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#4477]
## Description

The Airflow UI runs in light mode and it causes eye strain for people on the dark side.

## Reproduction

1. Run the Catalog quickstart guide and open the Airflow UI in the browser.
4. See the light mode user interface.

## Additional context

This issue was raised at contributor day.

**Comment by szymon-polaczy** [comment]
Hi @dhruvkb, I think that this will be taken care of shortly by the Airflow team as a PR was already merged https://github.com/apache/airflow/pull/39355

It just looks like it will be pushed in the 2.10.0 version instead of being pushed in latest ones - https://github.com/apache/airflow/milestone/90

It might be a bit too dark for some people but it should get better after version 3 is deployed https://github.com/apache/airflow/pull/39355#issuecomment-2195373222.

As this is taking place already is it a good idea to keep this issue open or maybe just creating this note that updating airflow should take care of it is enough?

**Comment by krysal** [comment]
Thank you for doing the research and sharing the info @szymon-polaczy. Let's close this and wait for the upstream update then.
