### ISSUE TITLE
The `AbstractMediaDecisionThrough` class and its inheriting classes shouldn't use actual foreign keys to media tables

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#4512]
## Description

When running the `backfillmoderationdecision` management command, it failed while bulk creating `MediaDecisionThrough` for images due to an image identifier not found in the image table. This is expected for the case of unindexed media (either because the medium disappeared from the source or because of a report), given that the entry is removed from the media table and the identifier moved to the `api_deleted<media>` table.

### Error

```python
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 218, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
    return instance._state.fields_cache[cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'media_obj'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/api/manage.py", line 29, in <module>
    main()
  File "/api/manage.py", line 25, in main
    execute_from_command_line(sys.argv)
  File "/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/api/api/management/commands/backfillmoderationdecision.py", line 96, in handle
    [
  File "/api/api/management/commands/backfillmoderationdecision.py", line 97, in <listcomp>
    MediaDecisionThrough(media_obj=report.media_obj, decision=decision)
                                   ^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 236, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 199, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
api.models.image.Image.DoesNotExist: Image matching query does not exist.
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
```

### Expected behavior

We want to drop the foreign keys so this error does not appear and the command can finish without issues and changes.

## Additional context

- Related to #3641
- [Sentry issue](https://openverse.sentry.io/share/issue/54999d982a814c0380005014b8c08ffa/).

**Comment by stacimc** [comment]
I'm not sure what you mean by "we want to drop the foreign keys".

From the IPs, my understanding is that when we make a decision that deindexes a record we want to have a reference to the `media_obj` on all decisions and reports, [even when the referenced media was deleted from its media table](https://docs.openverse.org/projects/proposals/trust_and_safety/content_report_moderation/20231208-implementation_plan_django_admin_moderator_access.html#moderationdecision).  We already allow this on the report model with `db_constraint=False` and I think we were supposed to support that on the ModerationDecision as well (although it looks like we [don't](https://github.com/WordPress/openverse/blob/79c3a67d8becbe3842d4c6ed129d6f97fbf50931/api/api/models/media.py#L356) 🤔).

So I think we need to:
* In the backfill command, get the 'plain' value of the media obj id from the MediaReport, rather than trying to get the instance (maybe `report.media_obj_id` rather than `report.media_obj`?)
* Update the `MediaDecisionThrough` model to have `db_constraint=False` <-- not sure if this requires a migration
* When creating the `MediaDecisionThrough` objects, pass the 'plain' value of the identifier (since there is no instance to pass) -- something like `MediaDecisionThrough(media_obj_id=report.media_obj_id ...)`

Does that sound correct? Cc @sarayourfriend as well

**Comment by krysal** [comment]
@stacimc you explained it better! I was referring specifically to the `db_constraint=False`, so your steps are correct. I didn't remember if that was possible in this case, but it looks like it is. Great.

**Comment by krysal** [comment]
@stacimc you explained it better! I was referring specifically to the part of the constraint, `db_constraint=False`, so your steps are correct. I didn't remember if that was possible in this case, but it looks like it is. Great.

**Comment by stacimc** [comment]
Perfect! Thanks for double checking me :)
