### ISSUE TITLE
Audio box layout cannot hold content at 1024px breakpoint with filters open

### ISSUE THREAD

**Issue by dhruvkb** [WordPress/openverse#455]
## Description

Openverse renders perfectly fine at 1024px when the filter sidebar is closed. But when you open the sidebar, the number of results per line is not reduced (presumably and understandably to reduce reflow), the boxed audio can no longer contain the title, category, license and player in the small square space.

## Reproduction

1. Go to https://staging.openverse.org
2. Search for some term in the mixed media results.
3. Resize the browser to 1024px, the smallest desktop breakpoint.
4. Open the filters sidebar.
5. See error.

## Screenshots

With the sidebar closed, everything looks OK:

![image](https://user-images.githubusercontent.com/16580576/217166140-2f02d2e9-a794-4383-8644-4e1e4b0c5980.png)

With the sidebar open, audio boxes are broken:

![image](https://user-images.githubusercontent.com/16580576/217166093-f3cb6fd6-22d9-4393-ac12-5511e9ec1fe8.png)

## Environment

- **Screen resolution:** 1024px
- **Conditions:** Sidebar open

**Comment by panchovm** [comment]
Since this is not a bug but a query definition, we might need to address this problem by tackling the grid behavior.

The current grid responds to breakpoint values rather than its container width, as opposed to audio results where audio components change when filter sidebar is open. In that vein, audio results grid solves this issue thoroughly and it might be timely to inherit part of that interaction.

## Grid columns based on its container

After reviewing the grid on each breakpoint, I noticed that some middle views display big boxes and do not shift to a different layout. Look how the current `sm` and `md` diplay the grid.

![CleanShot 2023-03-14 at 14 40 02@2x](https://user-images.githubusercontent.com/895819/225019306-bd990269-5b95-4be6-b332-54407dbdcc87.png)

If we change to a grid that adds or hides columns based on the container width, we can reach a cleaner grid where boxes convey the content they hold without problem. After some desing tests, I end up with the following set of mockups and the grid class per breakpoint.

![CleanShot 2023-03-14 at 14 48 43@2x](https://user-images.githubusercontent.com/895819/225021815-21e7d9a2-4e68-4905-9596-119993d290ed.png)

<img src="https://user-images.githubusercontent.com/895819/225022139-295d05f9-04cd-4f06-80c8-0813ea25de68.png" width="400">

The example attached above is based on breakpoints, but since the filter sidebar has a fixed-width value, we can safetly add / remove 2 columns based on its container without breaking the smooth transition. See how this change would look like in `lg` and `xl`.

### `lg`

![CleanShot 2023-03-14 at 15 04 20](https://user-images.githubusercontent.com/895819/225027935-c9e584e5-d038-4655-8747-73da11f4c56f.gif)

### `xl`

![CleanShot 2023-03-14 at 14 59 27](https://user-images.githubusercontent.com/895819/225027993-9e099a63-5612-4604-a688-f7543a589e0b.gif)

## New content link section

This idea also needs to address the content link section placed above. The current grid treats the layout according to those elements and, therefore, it would need a revamp of that whole section to prevent uneven alignments and become a permanent solution to all the upcoming content types we decide to support.

The current implementation also renders the grid oddly when filter sidebar is open. See how that sections looks like in `lg` breakpoint.

![CleanShot 2023-03-14 at 15 18 19@2x](https://user-images.githubusercontent.com/895819/225030085-f2ba487f-f982-401d-86fa-ed8799e7d045.png)

---

What do you think of this idea?
