### ISSUE TITLE
Flaky 503s when trying to fetch Freesound audioset info

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#4594]
## Description

Several production DagRuns of the Freesound workflow have failed due to intermittent 503s when trying to get audio set info, which succeed when the DAG is later manually retried. See July 2024 runs of the DAG for examples.

We could address this a couple of ways, given that the problem is intermittent:
* Add an additional `retry` to [get_set_info](https://github.com/WordPress/openverse/blob/f556ccfb6b108a76add2d448576feeea60b4df82/catalog/dags/providers/provider_api_scripts/freesound.py#L132) similar to the existing special handling of flaky exceptions on [get_audio_file_size](https://github.com/WordPress/openverse/blob/f556ccfb6b108a76add2d448576feeea60b4df82/catalog/dags/providers/provider_api_scripts/freesound.py#L160)
* Increase the number of timeouts overall for Freesound
* Keep track of records which 503 and skip them during ingestion, then automatically retry them once the rest of ingestion has finished. This is likely more effort than is merited.
* Worst case, discard individual records whose audio set info can't be obtained, and report the number of skipped records to Slack. This is better than continuing to use `SKIP_INGESTION_ERRORS`, which will cause an entire batch to be skipped when one record exceeds retries.

**Comment by AetherUnbound** [comment]
Looking at [the logs of a recent run](https://airflow.openverse.org/dags/freesound_workflow/grid?dag_run_id=manual__2024-07-02T18%3A13%3A03%2B00%3A00&task_id=ingest_data.pull_audio_data&tab=logs), it seems like the 503s and intermittent 400s (which are _very_ odd) are coming from both the base query endpoint and the audio pack endpoint. I'm wondering if the it might be best to try a 30 second pause for all `get_response_json` calls in Freesound when those two errors are encountered, just since we know that Freesound can be quite flakey here 🤔 I'm going to look into how easy that might be to do with the `@backoff` decorator.
