### ISSUE TITLE
Openverse.org embeds are not functioning

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#4602]
## Description

Embeds of Openverse.org links are not working.

## Reproduction

1.  Try linking Openverse.org (https://openverse.org/image/94cec95f-7b39-426c-8782-364f26f0243d for example) somewhere that supports embeds.
2.  See that it doesn't work.

I noticed this in Slack.

Are the OpenGraph tags working?

**Comment by szymon-polaczy** [comment]
Hi @sarayourfriend, I tried testing that url in this https://www.linkedin.com/post-inspector and got this error
_We did not re-scrape https://openverse.org/image/94cec95f-7b39-426c-8782-364f26f0243d because the URL or one of its redirects is blocked by rules set in robots.txt file ofits URL domain._

I then looked into the code of the page and saw that the og:image was there and loading
`<meta data-n-head="ssr" data-hid="og:image" property="og:image" content="https://api.openverse.org/v1/images/94cec95f-7b39-426c-8782-364f26f0243d/thumb/">`

I think that this isn't an og issue but a robots.txt issue as you can even see that /image/ is disallowed
robots.txt - `Disallow: /*/image/`

**Comment by sarayourfriend** [comment]
Just to confirm (I don't see it written anywhere), the embed is working now since #4660.
