### ISSUE TITLE
Sources table does not show the full URL in mobile size

### ISSUE THREAD

**Issue by kajalmultidots** [WordPress/openverse#470]
## Description

In the below URL, the table content is not showing properly in the responsive(320px) design.
Page URL: https://wordpress.org/openverse/sources/

For better understanding, I provided the Video attachment
Video URL: https://share.cleanshot.com/N09QQ0MzRdKvJ4fZkV8t

Thanks.

## Implementation
[Designs](https://www.figma.com/file/b28hEVRNa6ipHQ45IFIB7G/Responsive-source-tables?type=design&node-id=22-13656&mode=dev) were cleaned-up for dev, and are ready for implementation.

Component to update: `frontend/src/components/VSourcesTable.vue`

**Comment by fcoveram** [comment]
Here are two ideas where I would like your thoughts.

## Stacked rows

Stack each row when the screen reaches the `sm` breakpoint.

| `sm` breakpoint | `xs` breakpoint |
|:---|:---|
| <img width="640" alt="Source page with stacked table in SM breakpoint" src="https://github.com/WordPress/openverse/assets/895819/de8ebc2c-c47e-4c00-8a23-70f687dff6ad"> | <img width="320" alt="Source page with stacked table in XS breakpoint" src="https://github.com/WordPress/openverse/assets/895819/eb460460-cc1c-46c9-862a-c80f6e2f8c2a"> |

One benefit is that all info is displayed on the page without additional scroll bars. Even when columns are not sortable, I'm drawn to this solution as data is not in a comparison or evaluation context; in contrast to other spreadsheets like sales or number evolutions where cells side by side ease the table meaning.

I found [this example](https://codepen.io/smashingmag/pen/bGKBNNr) from [this](https://www.smashingmagazine.com/2022/12/accessible-front-end-patterns-responsive-tables-part1/) Smashing magazine post for reference.

## Scrollbar table

A second alternative could be to make the table scrollable horizontally and add a shadow indicating the scroll direction.

| `sm` breakpoint | `xs` breakpoint |
|:---|:---|
| <img width="640" alt="Source page with a scrollable table in SM breakpoint" src="https://github.com/WordPress/openverse/assets/895819/c70b8b3a-fe4e-4ccf-a862-c662a7f1ecd5"> | <img width="320" alt="Source page with a scrollable table in XS breakpoint" src="https://github.com/WordPress/openverse/assets/895819/6f3055a5-ab65-4bce-add0-977950abb272"> |

I personally don't like this alternative as on small screens the interaction feels clunky due to the bi-directional scrollbar in small screens.

What do you think of this?

---

## Updates from Design Library

In addition to the above, I applied spacing tweaks based on the latest updates in the Design Library. The main changes are:
* In `2xl / xl / lg`
   * Content wrapper has a max-width of `768px`
   * Margin top is `40px` and bottom `96px`
* In `md / sm`
   * Margins: top is `20px`, sides and bottom are `40px`
* In `xs`
   * Margins: top is `20px`, sides are `24px`, bottom is `40px`

## Designs

Figma file: [Responsive source tables](https://www.figma.com/file/b28hEVRNa6ipHQ45IFIB7G/Responsive-source-tables?type=design&node-id=22-13656&mode=dev)

**Comment by zackkrida** [comment]
Hi @kajalmultidots, do you have any feedback concerning the [design proposal](https://github.com/WordPress/openverse/issues/470#issuecomment-1855733379) for the issue you raised?

@fcoveram, if we don't get any community feedback on this particular issue I think you can pick whichever you prefer and mark this ready for work.

**Comment by krysal** [comment]
I greatly like the stacked rows; they look more appropriate for a small screen. Horizontal scrolling can sometimes be problematic on the phone, as Android uses that gesture to go back to pages or apps.

**Comment by fcoveram** [comment]
Seeing the mockups after a month of sharing them, and I agree with @krysal that stacked rows looks better. Let's go with that one.

[Designs](https://www.figma.com/file/b28hEVRNa6ipHQ45IFIB7G/Responsive-source-tables?type=design&node-id=22-13656&mode=dev) were cleaned-up for dev.

**Comment by szymon-polaczy** [comment]
Hi, Is this something I could help with?

**Comment by krysal** [comment]
@szymon-polaczy It's up for grabs if you like!

**Comment by szymon-polaczy** [comment]
Great, in that case I'd like to snatch it

**Comment by kajalmultidots** [comment]
Hi @zackkrida ,

sorry I missed your message. I think @fcoveram provided the design mockup is looks good. Great work @fcoveram 🎉 .

Thanks all for your work 👍
