### ISSUE TITLE
Do not log timeout errors for upstream thumbnail exception

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse#4774]
## Current Situation

#4748 decreased the timeout for upstream thumbnail requests. Upstream timeout errors are being recorded as issues in Sentry along with all other [UpstreamThumbnailExceptions](https://github.com/WordPress/openverse/blob/5e2e0e308a3f26cf87edc731287aaac8b17117d4/api/api/utils/image_proxy/extension.py#L62).

## Suggested Improvement

We shouldn't logger.error TimeoutErrors. See #4757 for example where we omit these.

## Additional context

https://openverse.sentry.io/share/issue/309a511cd431430aa2123ee7d1b37d91/

**Comment by sarayourfriend** [comment]
I mentioned this in Slack, but we should look at the possible errors that can happen and decide which ones we actually think are potentially actionable vs always noise, and then only logger.error the subset we want in Sentry, and logger.warning the rest.

While we're at it, we can delete the tallying code for these exceptions in the thumbnails. We have never consulted them and as written the keys are pretty useless and potentially take up a huge amount of space in Redis anyway. It would be far more useful in the logs where we can actually query them and we have an in-built rotation mechanism so they aren't just indefinitely piling up.

I'd like the fix for this to take that into account, or else I can create a separate issue for all that if we want to just exclude timeout errors... it'd be far more useful to us in our Sentry volume if we went ahead and addressed the entire scope of the problem though (in all places where we logger.error for upstream provider requests).

**Comment by sarayourfriend** [comment]
@WordPress/openverse-api does anyone have input here? This feels important to take care of to avoid Sentry filling up with unactionable issues, and to clarify the intention in the thumbnail and dead link request areas.

**Comment by stacimc** [comment]
+1 to everything you've said, @sarayourfriend. As to the tallying, I've never looked at it -- pinging @AetherUnbound just in case, I think she might have? Although I could be thinking of the other tallies.

Should we go through Sentry to build the list of possible errors and make the call on noise/actionable?

**Comment by AetherUnbound** [comment]
I have seen this and will respond to this discussion when I have time!

**Comment by AetherUnbound** [comment]
We just received notice from Sentry that our quota is filling up as a result of these and that we may hit our limit soon. I think removing the tally code can be a separate issue & discussion. 

On which errors to ignore, I think we can make a change to ignore the following to start (with more to potentially be added later):
- `ClientConnectorCertificateError` ([1](https://openverse.sentry.io/issues/5713009645/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0), [2](https://openverse.sentry.io/issues/5802369407/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=5))
- `ClientConnectorError` ([1](https://openverse.sentry.io/issues/5734948588/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=1), [2](https://openverse.sentry.io/issues/5713220271/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=2), [3](https://openverse.sentry.io/issues/5724302617/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=8))
- [`ClientConnectorSSLError`](https://openverse.sentry.io/issues/5713017654/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=4)
- `ServerDisconnectedError` ([1](https://openverse.sentry.io/issues/5713868139/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=3), [2](https://openverse.sentry.io/issues/5715026182/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=6))
- [`RuntimeError`](https://openverse.sentry.io/issues/5714931147/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=9)
- `ClientOSError` ([1](https://openverse.sentry.io/issues/5715342472/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=11), [2](https://openverse.sentry.io/issues/5790829654/?environment=production&project=6107216&query=&referrer=issue-stream&statsPeriod=14d&stream_index=15))

That's not exhaustive but would be a good start.
