### ISSUE TITLE
Incorrect CORS variable definition in docker.env

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#4974]
## Description

A user has [reported](https://wordpress.slack.com/archives/C02012JB00N/p1727104742622669?thread_ts=1727080329.964219&cid=C02012JB00N) an issue with our `docker/es/env.docker` file:

> a issue i got after that was regarding
> http.cors.allow-origin="/.*/"
> in docker.env
> it wasn't expecting "-" as valid string i have to change it to
> http_cors_allow_origin=/.*/="/.*/" 
> then it was working fine

Note that this user is using WSL which could potentially be related. Otherwise it would seem that multiple of the values in our Elasticsearch docker.env file are invalid:

https://github.com/WordPress/openverse/blob/9525973401e86c664571fb040d1ec86a7a837ae1/docker/es/env.docker#L1-L14

**Comment by sarayourfriend** [comment]
This is a docker compose bug, which should be fixed by upgrading to the latest compose once it comes out: https://github.com/docker/compose/issues/12123

I'm seeing this locally now after running `ov init` (not on WSL).

We can either:
0. Versionlock Docker compose to the version before this bug (flaky long-term)
1. Convert this env.docker file to a real Elasticsearch configuration file
2. Update all the environment variables to use Elasticsearch's actual environment variable rules, which are listed here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods

The last option is the easiest, but ultimately hurts discoverability of what those options mean (much harder to search ES docs or the web), so I'd only consider it a stop-gap to using a regular Elasticsearch configuration file.
