### ISSUE TITLE
Page for 'not supported' / 'coming soon' content types

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#507]
## Problem

We need to design and implement a page for the 'not supported' / 'coming soon' content types we would like to show in the content switcher. At the time of writing those are 3D models and video. Adding these pages will help us get a sense of interest in these content types. We can also show external sources for these content types in the meantime to help users.

## Description

@panchovm started a design for these pages, but it needs to be updated and finished now that we've updated the copy and styling of the 'external sources' feature. Here's an example mockup he provided as a starting point:

![181094969-ca8fc34c-4f00-4028-9271-40afa6f0cf58](https://user-images.githubusercontent.com/6351754/188705477-49493865-f240-4370-8a85-70153aefe950.png)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by panchovm** [comment]
Since no "coming soon" content type is displayed on the current site, does this problem still apply?

**Comment by zackkrida** [comment]
@panchovm yes, we need to build the pages before we can show those links for new media types. Do you think [these designs](https://github.com/WordPress/openverse/issues/507#issuecomment-1439708787) are still correct or do we need to make revisions?

**Comment by Tomvth** [comment]
Hello @zackkrida , I would be interested in contributing to this issue. Could you please assign it to me?

**Comment by panchovm** [comment]
Those designs definitely need an update @zackkrida 

That update is mostly about text style and buttons, the layout grid can be the same. And since Core UI improvement project (#415) plans to update the button component, I would block this change until the improvement is done.

The Figma button component is done, so for now you can contribute @Tomvth with creating the design file and picking the correct button style for this page. Otherwise, let's block this ticket until #415 is done
