### ISSUE TITLE
Switch to `ENTRYPOINT` instead of `CMD` in our Dockerfile

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse#522]
## Description

We would like to switch to using `ENTRYPOINT` instead of `CMD` in our Dockerfile because entrypoint accepts arguments without also requiring you to replace the entire command. [This article](https://aws.amazon.com/blogs/opensource/demystifying-entrypoint-cmd-docker/) explains the difference between the two well and makes recommendations:

> if we pass non-option arguments to docker run, they will override the value of CMD.

> If your image is built to do only one thing — for example, run a web server — use ENTRYPOINT to specify the path to the server binary and any mandatory arguments. A textbook example of this is the nginx image, whose sole purpose is to run the nginx web server. This lends itself to a pleasant and natural command line invocation: docker run nginx. Then you can append program arguments naturally on the command line, such as docker run nginx -c /test.conf – just like you would if you were running nginx without Docker.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

**Comment by krysal** [comment]
@zackkrida is this required for the production image? Since we're not recommending the docker setup for development it seems to me that we should close this issue but to be sure, do you still see a necessity here?

**Comment by zackkrida** [comment]
Actually, we've already implemented this on the frontend, so it might be nice to use this issue to address making the same change on the API. CC @AetherUnbound as she's been working with the API docker setup lately.

**Comment by AetherUnbound** [comment]
We actually already have an entrypoint for the API! ([file is here](https://github.com/WordPress/openverse/blob/main/api/run.sh))

https://github.com/WordPress/openverse/blob/94246bf151390c4346830e5df1cc7e928f4a43a4/api/Dockerfile#L110-L113

One thing we could do is put the CMD as the default action in the entrypoint in case no arguments are supplied, that way we wouldn't need to specify a CMD at all. But that just seems to be a matter of changing where something is defined rather than altering behavior, since we already support the entrypoint approach as-is. For the API we are much more frequently _changing the command entirely_ rather than adding options to an existing command, so I'm not entirely sure the use case laid out in the description would even be beneficial for us with the API 🤷🏼‍♀️

**Comment by AetherUnbound** [comment]
Actually, we override the command anyway for production, and again it ends up being entirely different rather than a modification of this command:

https://github.com/WordPress/openverse-infrastructure/blob/db31bcb394864b3362e06504195e7ed88e30ee36/next/modules/concrete/api/main.tf#L167-L169

(for those without access, the command becomes `[ "gunicorn", "--chdir=/api", "--bind=0.0.0.0:8000", "--workers=4", "catalog.wsgi", ]`)

So I think we can probably just close this WRT the API!
