### ISSUE TITLE
Meta search should be disabled on all content results

### ISSUE THREAD

**Issue by fcoveram** [WordPress/openverse#533]
## Description
In all content results, the meta search section is visible at the end of the grid. This should be disabled as the section was designed to list sources related to a single content type and not multiple, as in this layout case. This logic applies to the outdated and the new design.

## Reproduction
1. Search for something.
2. Go or switch to All content results.
3. See the final section, after the results grid.
4. See the meta search section.

## Screenshots
<img width="1000" alt="CleanShot 2022-07-26 at 09 43 45@2x" src="https://user-images.githubusercontent.com/895819/181020944-6ff8ef7d-e362-4400-9b28-0dd01dcb5bdd.png">

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

**Comment by obulat** [comment]
@fcoveram, what if instead of hiding this on all results views, we show all of the external sources there? And to make it clear which media type the source has, we add a content type icon to the button (or another indication)? I tried adding it to the new popover:
<img width="476" alt="Screenshot 2023-07-19 at 10 50 13 AM" src="https://github.com/WordPress/openverse/assets/15233243/b9c858a1-8ae7-41ac-9a97-05e165193b65">

**Comment by fcoveram** [comment]
All my points shared in previous messages on why not showing this component are rooted in the usefulness of this element and the idea of keeping a simple design. It's not about its visual style.

I thought we concluded this conversation with this message from Zack:

> I am fine with hiding it on the 'all results' view and unblocking this, however. Once we make progress on some analytics work and find out how often this feature is actually used, we'll be better able to make decisions about where to display it.
