### ISSUE TITLE
Add types to `server-middleware/healthcheck.js`

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#614]
## Description

Add type checking to `healthcheck.js`. This module has zero dependencies. Make sure to add it to `tsconfig.json`'s `include` list.

Note: The exported function should be typed using `@nuxt/types`'s `ServerMiddleware` type.

## Additional context

Part of an ongoing effort to add type checking to parts of the project that can be type checked.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by ngken0995** [comment]
@sarayourfriend I notice on [tsconfig.json](https://github.com/WordPress/openverse/blob/c47c8d9bf5ec2e5fe3ed456bb9261d4371651a2f/frontend/tsconfig.json#L39) `server-middleware/healthcheck.js` is included. [Healthcheck](https://github.com/WordPress/openverse/blob/c47c8d9bf5ec2e5fe3ed456bb9261d4371651a2f/frontend/src/server-middleware/healthcheck.js#L6) has a type to specific the type of the function. Do I need to add typeof or another function for type check?

**Comment by dhruvkb** [comment]
If the file has `@type` in the documentation comment and is included in `tsconfig.json`, it is already being type-checked by TypeScript. It means that this issue has already been resolved.

This was fixed by https://github.com/WordPress/openverse-frontend/pull/1717. Since that PR did not reference the issue, it might have been accidentally been left open at the time. Thanks for noticing this @ngken0995!
