### ISSUE TITLE
Unhandled error when database connection is not available

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#671]
## Sentry link

(Redacted for security reasons, contact staff if you're interested)
Private link: https://sentry.io/organizations/openverse/issues/3599736424/?project=6107216

## Description

Presently if the database connection disappears, the `/healthcheck/` endpoint (and others) will raise an `OperationalError`. 

~~Catch this particular exception and return a 424 and log the OperationalError (potentially send it to Sentry as well). This might signal to AWS that the service needs to be replaced though, which wouldn't necessarily correct the underlying issue[^1].~~

~~We should catch the exception _only during the API database's known maintenance window_. That was what instigated these Sentry events, but again that'd still raise an unhandled exception. Interested to hear what folks think the best approach here might be @WordPress/openverse-api.~~

Rather than trying to mask the issue during the maintenance window, we should instead investigate ways to prevent any downtime on our database whatsoever while maintenance is occurring. This might involve replication or some other means AWS has for preventing database downtime.

[^1]: While this masks the issue, we have other alarms that let us know when load balancers report targets as unhealthy. In other words, this isn't an issue unless we expect those alarms to fail.

## Reproduction

1. `just up`
1. `docker stop openverse-api-db-1`
1. Visit http://localhost:50280/v1/images/

**Comment by AetherUnbound** [comment]
This occurred again recently on this particular, but we believe it was triggered by high traffic which overwhelmed DNS rather than the DB itself being unavailable.

**Comment by krysal** [comment]
@sarayourfriend Do you mean to raise a `424 Failed Dependency` error instead of the `429 Too Many Requests`? The `429` will pass the health check as [healthy](https://github.com/WordPress/openverse-infrastructure/blob/4307a2f0871acc972bf42b77769bd0519671213b/next/modules/concrete/api-thumbnails/main.tf#L138).

**Comment by sarayourfriend** [comment]
Whoops, yes, I meant 424, not 429 :+1:

**Comment by sarayourfriend** [comment]
@AetherUnbound Can you clarify what you meant by this?

> We should catch the exception _only during the API database's known maintenance window_. That was what instigated these Sentry events, but again that'd still raise an unhandled exception. Interested to hear what folks think the best approach here might be @WordPress/openverse-api.

Did you mean for us to catch the error and silently handle it during the maintenance window? And then for other cases, just let the existing 500 happen (treating those 500s as a correct signal of service healthcheck failure)?

That _sounds_ good to me, but also could be tricky if we're suddenly juggling too many conditions in what is ideally a difficult-to-get-wrong route :grimacing:.

If that is the approach you were considering, though, I'm confused why the maintenance window causes OperationalErrors. Is there something _else_ we should be doing for our database to be resilient in the face of maintenance windows so that we get as close to 100% uptime on our database connections? It's weird that the database connections would be expected to fail once a week during that window...

**Comment by AetherUnbound** [comment]
Yes, that was my intention with the original approach, but frankly the more appropriate route would be to make our API RDS instance robust to system maintenance (either by replication or some other method). As you mention, this will become more necessary as we get more traffic, since we can't expect our entire service to be down for the maintenance window once a week. I'll modify this ticket's description so that it instead includes an investigation into alternative methods for managing uptime.
