### ISSUE TITLE
Prevent divergent migrations from being merged by concurrent, not-rebased PRs

### ISSUE THREAD

**Issue by sarayourfriend** [WordPress/openverse#687]
## Problem

See https://github.com/WordPress/openverse-api/pull/810 and the description for the issue.

## Description

We need some way to prevent this.

Here are some suggestions I left in this comment, copied below: https://github.com/WordPress/openverse-api/pull/810#issuecomment-1191503799

> How can we prevent this? Is there any way we can ensure PRs with migrations are always rebased before merging? Could we run an action triggered by pushes that introduce new migrations using https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files and the iterate through all open, non-draft PRs and request changes on them if there is a migration in them?
> 
> We'd also need a similar job in the CI + CD workflow to check for migration conflicts against main any time the PR is pushed to.

Marked as high due to the risk it introduces.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
I think this can be implemented automatically using merge queues (provided we ensure that maintainers put PRs with migrations into a merge queue instead of merging directly).

From [the docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues)

> The merge queue will ensure the pull request's changes pass all required status checks when applied to the latest version of the target branch and any pull requests already in the queue.

This would mean that the merge queue would run CI + CD *right before* merging the PR which means
- the migration is either valid and CI + CD passes and the PR is immediately merged into `main`
- the migrations have diverged, CI + CD would fail and the merge would be cancelled.

This differs from regular branch checks in that the merge queue checks are run just before merging (and can cancel a merge in progress), whereas branch checks run at PR creation or update time and the state of `main` can have changed between the branch checks being run and the PR getting merged.

**Comment by tylerlaprade** [comment]
A simple approach is this plugin which we've been using for a year now: https://github.com/crux-lab/django-migrations-git-conflicts
It writes the latest migration to a text file, so if migrations aren't merged, that file will have a git conflict.
