### ISSUE TITLE
Rename the "ingestion server" to "data refresh"

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse#730]
## Problem

We are using the legacy name "ingestion server" for a server that is performing our data refreshes (see https://github.com/WordPress/openverse/discussions/107).

## Description

I would like to propose that we rename the ingestion server and all associated assets (Docker images, private DNS names, references, etc.) to "data refresh" or "data refresh server". This will make it clearer what action the server is performing, particularly since we are still overloading the term "ingestion". Renaming it to `data_refresh` also helps us remove the redundant `_server` suffix everywhere.

## Alternatives

If anyone is **against** this change or would like to propose an alternate name, please do so by **2022-03-04**.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
@AetherUnbound Is this still worth the complexity to do? Changing the name everywhere would require code, infrastructure, and documentation changes. From my perspective, the relative weirdness of the name "ingestion server" doesn't cause very many issues. Is all the work that would be required for this (probably including an implementation plan, to make sure we covered all the bases) be worth it? How often does this cause a significant confusion? In my experience legacy names, if they aren't hurting anything, are usually something worth just living with rather than the serious headache it usually takes to "fix" them.

**Comment by AetherUnbound** [comment]
Agreed, at this point I'd much rather see this functionality pulled into the data refresh process of Airflow than us spend effort renaming this service. I'll close it!
