### ISSUE TITLE
Skip frontend docker image build and its tests on non-frontend code changes

### ISSUE THREAD

**Issue by krysal** [WordPress/openverse#849]
## Description

Currently there are some steps of the **CI + CD** workflow that run for all PRs when they shouldn't, namely:
- CI + CD / Run frontend unit tests (pull_request)
- CI + CD / Check Storybook smoke test (pull_request) 
- CI + CD / Check Nuxt build (pull_request)
- CI + CD / Build `frontend` Docker image (pull_request)

Also, it looks like the frontend image is duplicated with different names?

## Reproduction

Look at the checks pf any other PR in the repository that does not change frontend code.

## Screenshots

Screenshots taken at #836 before merging.

![Screenshot 2023-03-06 at 11-51-58 Bump python-decouple from 3 7 to 3 8 in _api by dependabot bot · Pull Request #836 · WordPress_openverse](https://user-images.githubusercontent.com/9145885/223162739-d572c81c-2822-4fb8-8881-0292ff020a15.png)
![Screenshot 2023-03-06 at 11-55-03 Bump python-decouple from 3 7 to 3 8 in _api by dependabot bot · Pull Request #836 · WordPress_openverse](https://user-images.githubusercontent.com/9145885/223162749-b48f9d6b-0119-42ad-944b-dffb8228c4d4.png)

## Environment
GitHub Actions.

**Comment by dhruvkb** [comment]
For context, I let the frontend unit tests run because they are not time consuming and they're not flaky. The same for API tests like Django check and migrations. 

Only time consuming tests like VR, e2e and API integration were made conditional.

The build for the frontend image is also parallelised so while not necessary, it does not slow down the CI workflow.

That said, I'm onboard with the idea of reducing redundant jobs.
