### ISSUE TITLE
Dead thingiverse images are not filtered out because they return 403

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse#900]
## Description

When we filter dead links, we do not mark image as dead when the direct URL returns 403 or 429 because that might be caused by the provider rate limiting. However, for Thingiverse, a 403 should probably be a reason for marking the link as dead. Otherwise, we get a lot of dead links on the frontend.

## Reproduction

1. Search for cat images.
2. Select the `Thingiverse` source filter.
3. You should see an "Image not available" thumbnail as the first result. There are more than 5 such thumbnails in the first 3 pages. If you click on "Get this image", you get to a 404 page. And the direct URL returns 403.
[API result for such an image](https://api.openverse.engineering/v1/images/236f4e8d-92a7-44ac-9283-0c5bce26f23d/)

## Screenshots

<img width="1327" alt="Screenshot 2023-03-13 at 9 34 09 AM" src="https://user-images.githubusercontent.com/15233243/224625090-aa2eb0e5-881f-4c18-a91b-6d848dfbb5ab.png">

## Additional context

There might be other providers who return 403 for dead links.

I marked this as low as I only know of one provider that this issue affects, and it's usually not very prominent in the results.

**Comment by sarayourfriend** [comment]
@obulat @zackkrida do y'all have specific ideas for how that change would work? It seems like a much bigger change than is necessary to fix this particular issue, which I think can be fixed by just adding a check on the provider of the result when checking the status code:

```diff
diff --git a/api/catalog/api/utils/validate_images.py b/api/catalog/api/utils/validate_images.py
index 1bfcab7a..980bce14 100644
--- a/api/catalog/api/utils/validate_images.py
+++ b/api/catalog/api/utils/validate_images.py
@@ -119,7 +119,7 @@ def validate_images(
     for idx, _ in enumerate(cached_statuses):
         del_idx = len(cached_statuses) - idx - 1
         status = cached_statuses[del_idx]
-        if status == 429 or status == 403:
+        if status == 429 or status == 403 and results[del_idx]["provider"] != "thingiverse":
             logger.warning(
                 "Image validation failed due to rate limiting or blocking. "
                 f"url={image_urls[idx]} "
```

I'm fine with the idea that we could expand the ways we record dead links, but in the interest of fixing this bug I don't want to blow the scope of the issue out of the water into something that probably needs a thoughtful proposal rather than an ad-hoc change.

@krysal Can you clarify why the issue was re-prioritised? My suggestion mostly stems from the issue being "high", as that suggests we shouldn't delay fixing it.

**Comment by krysal** [comment]
> @krysal Can you clarify why the issue was re-prioritised?

The issue suggeted a flaw in the logic to identify dead links. If we have provider API keys why don't we use them in this check? Is it because we risk consuming the quota and hindering ingestion? If that is the case then this is a hard problem, would be interesting to discuss it during the [project](https://github.com/WordPress/openverse/issues/428).

Also, that placeholder image is ugly enought to make me want to get rid of those **bad results** as soon as possible. I tried the same [`cat` search for Thingiverse](https://openverse.org/search/image?q=cat&source=thingiverse) and the first one was a broken image.

What priority would you have given it, @sarayourfriend? Your proposed solution sounds good for this specific case, and we can generalize it later with something like @zackkrida proposes if other cases arise.

**Comment by sarayourfriend** [comment]
> What priority would you have given it, @sarayourfriend?

High makes sense to me, but the conversation didn't appear to reflect it (scope of the fix was potentially increasing). I just wanted to confirm if there'd been discussion elsewhere about it (given it was specifically reprioritised without an explanation, I figured it might have happened during a sync discussion).

I can have a PR for the ad-hoc solution up later today.

**Comment by krysal** [comment]
My bad that I didn't comment on priority rising 😅 I had my hands full at the moment. I'll remember to come back and leave notes the next time.
